### ISSUE TITLE
incorrect detection of int 0x80 syscalls on x86_64

### ISSUE THREAD

**Issue by nrdmn** [strace/strace#103]
On x86_64, strace is using linux' 64 bit syscall numbers to look up 32 bit syscalls made in a 64 bit binary. I'm using strace 5.1.

Code to reproduce:
```asm
.section .text
.global _start
_start:

mov $4, %eax
mov $1, %ebx
mov $hello, %ecx
mov $14, %edx
int $0x80

mov $1, %eax
mov $0, %ebx
int $0x80

hello: .ascii "hello, world!\n"
```

Compile and run with
```
as --64 -o hello.o hello.S && ld -melf_x86_64 -o hello hello.o && strace ./hello
```

Output:
```
execve("./hello", ["./hello"], 0x7ffc3412a900 /* 46 vars */) = 0
stat(NULL, hello, world!
NULL)                        = 14
write(0, NULL, 14)                      = ?
+++ exited with 0 +++
```
Instead of `write` and `exit`, strace detects `stat` and `write`.

**Comment by ldv-alt** [comment]
This is fixed in strace-4.26, but you need a kernel with PTRACE_GET_SYSCALL_INFO support, e.g.
linux-next or linux-5.3.

See also https://github.com/strace/strace/blob/master/tests/int_0x80.test
