### ISSUE TITLE
5.2: test suite fails

### ISSUE THREAD

**Issue by kloczek** [strace/strace#105]
test-suite.log in attachment
[test-suite.log](https://github.com/strace/strace/files/3388968/test-suite.log)

**Comment by esyr** [comment]
`++ sed -r -n 's/#define[[:space:]]*COPYRIGHT_YEAR[[:space:]]*"([^"]*)".*/\1/p' ../../config.h`
`+ config_year=`
`+ '[' 2019 -ge '' ']'`
`./strace-V.test: line 36: [: : integer expression expected`
`+ echo 'The year derived from config.h () does not pass sanity checks.'`
May I ask you to provide `config.h` from the build tree?

`BPF_MAP_CREATE failed: Operation not permitted`
This one can occur when locked memory limit (`ulimit -l`) is too tight and/or number of make jobs is too high (each map requires one page of locked memory, at least, and it is (counter-intuitively) accounted for all user's tasks and not for each task separately).

`BPF_PROG_LOAD failed (log: ""): Bad address`
This one is strange. On what kernel are you running the test suite?

**Comment by kloczek** [comment]
Kernel 5.1.5
I'm running test suite with -j48 on box with 128GB RAM.

[config.h.txt](https://github.com/strace/strace/files/3389379/config.h.txt)

**Comment by kloczek** [comment]
I would like to test those patches but now strace does not build for me.
https://github.com/strace/strace/issues/110

**Comment by esyr** [comment]
strace 5.3 has been released, you might want to try it to see if it solves the observed issues.

**Comment by kloczek** [comment]
Closing.
