### ISSUE TITLE
sourceforge has ./configure

### ISSUE THREAD

**Issue by jessfraz** [strace/strace#107]
I was just wondering why when I download strace off of sourceforge I already get the ./configure. Where as if I try to build from the source here, my instinct is to run aclocal, but it turns out that is not correct. My next instinct is to read `README-configure` which is also not correct.... then I realize based off a different issue the source of truth is in `INSTALL-git.md` which leads me to `./bootstrap`.

So I am assuming that you all also own the sourceforge. So why not also keep the configure in the repo here, or eliminate the need for the `sed`s, also wondering the "why" for that. And why sourceforge not github seems to be the best place to get the source for strace from.

Anyways, thanks for the transparency here, would really love to know why :)

**Comment by dirtyharrycallahan** [comment]
"configure", "Makefile", ... are dynamically generated artifacts so it would not make sense to keep them in a git repository. It is a very common way to organize a source tree.

**Comment by vapier** [comment]
the generated autotools files have never been committed to git in either SF or GH

if you're referring to the release tarballs, the ones in GH also contain the generated autotools files.  for example the latest release:
https://github.com/strace/strace/releases/download/v5.2/strace-5.2.tar.xz

what download are you referring to specifically ?

**Comment by jessfraz** [comment]
Gotcha, mostly wondering if you could make it more apparent to users that they need to run the custom script `./bootstrap` since `INSTALL-git.md` is not really apparent to end users.

**Comment by vapier** [comment]
users shouldn't be downloading tarballs that don't are missing generated autotools (e.g. `configure`).  which means they shouldn't have to know about `./bootstrap` or `INSTALL-git.md` in the first place -- by the time you've gotten that far, it's already too late.

what release exactly are you downloading and how did you get there ?
