### ISSUE TITLE
strace does not decode io_uring related syscalls

### ISSUE THREAD

**Issue by anarazel** [strace/strace#109]
Hi,

E.g. when using this example fio (https://github.com/axboe/fio/) file:

```
[global]
name=fio-drain-bug

size=1G
nrfiles=1

iodepth=2
ioengine=io_uring

[test]
rw=randread
``

I see 
```
[pid 17494] syscall_0x1a9(0x2, 0x7ffe9fe10cd0, 0x6, 0x561f64bc7730, 0x561f64bb7ce0, 0x2000) = 0x3
...
[pid 17494] syscall_0x1aa(0x3, 0x1, 0, 0x1, 0, 0) = 0x1
[pid 17494] syscall_0x1aa(0x3, 0x1, 0, 0x1, 0, 0) = 0x1
[pid 17494] syscall_0x1aa(0x3, 0, 0x1, 0x1, 0, 0) = 0
[pid 17494] syscall_0x1aa(0x3, 0x1, 0, 0x1, 0, 0) = 0x1
```

instead of io_uring_setup and io_uring_enter respectively.

**Comment by anarazel** [comment]
User error :(

**Comment by x77a1** [comment]
What was the user error? I am facing similar issue.

**Comment by x77a1** [comment]
I was able to fix the issue by upgrading to the latest verion of strace (5.6). (Posting it here incase it is useful for others facing similar issue).

**Comment by esyr** [comment]
On Sat, May 30, 2020 at 8:44 AM gourav <notifications@github.com> wrote:
> What was the user error? I am facing similar issue.

Using a version of strace older than 5.1, probably, as the syscall
didn't exist before Linux 5.1.

-- 
Eugene Syromyatnikov
mailto:evgsyr@gmail.com
xmpp:esyr@jabber.{ru|org}

**Comment by anarazel** [comment]
Yea, I'd rebuilt a new version of strace, but somehow managed to invoke the wrong version when testing io_uring.
