### ISSUE TITLE
Issue when installing: 

### ISSUE THREAD

**Issue by PenelopeFudd** [strace/strace#11]
Problem encountered when installing on Amazon Linux 2012.03:
```
$ ./bootstrap
...
generating ./xlat/.gitignore
generating ./xlat/Makemodule.am
m4/ax_valgrind_check.m4:105: warning: macro `AM_EXTRA_RECURSIVE_TARGETS' not found in library
m4/ax_valgrind_check.m4:144: warning: macro `AM_EXTRA_RECURSIVE_TARGETS' not found in library
configure:3948: error: possibly undefined macro: _AC_CC
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure:34732: error: possibly undefined macro: AM_EXTRA_RECURSIVE_TARGETS
autoreconf: /usr/bin/autoconf failed with exit status: 1

$ autoreconf --version | head -n 1
autoreconf (GNU Autoconf) 2.63
```

Only a warning on Amazon Linux 2017.03:
```
$ ./bootstrap

generating ./xlat/.gitignore
generating ./xlat/Makemodule.am
Makefile.am:895: warning: variable 'ioctlsort_LDFLAGS' is defined but no program or
Makefile.am:895: library has 'ioctlsort' as canonical name (possible typo)

$ autoreconf --version | head -n 1
autoreconf (GNU Autoconf) 2.69
```

I tried copying the source rpm for autoconf and m4 to the older system and rebuilding them, then installed the perl-macros rpm (with --force or else I'd have to rebuild all of perl).  The autoconf rebuild had a single failing test (#209: parallel autotest and signal handling, autotest.at:1616), which I "fixed" by adding "|| exit 77" to that test and rebuilding the rpm.

And then the ./bootstrap command still died with the same error after all that.  :-(

Can you suggest a way forward?

Thanks!

**Comment by ldv-alt** [comment]
GNU automake >= 1.13 is required to use AM_EXTRA_RECURSIVE_TARGETS macro.
