### ISSUE TITLE
5.2: build fails

### ISSUE THREAD

**Issue by kloczek** [strace/strace#110]
<pre>gcc -DHAVE_CONFIG_H   -I./linux/x86_64 -I./linux/x86_64 -I./linux -I./linux -I. -I.      -Wall -Wempty-body -Wformat-security -Wignored-qualifiers -Wimplicit-fallthrough=5 -Winit-self -Wlogical-op -Wmissing-parameter-type -Wnested-externs -Wold-style-declaration -Wold-style-definition -Woverride-init -Wsign-compare -Wtype-limits -Wwrite-strings   -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -flto -c -o strace-v4l2.o `test -f &apos;v4l2.c&apos; || echo &apos;./&apos;`v4l2.c
In file included from <b>./static_assert.h:11</b>,
                 from <b>xlat/v4l2_pix_fmts.h:4</b>,
                 from <b>v4l2.c:59</b>:
<b>xlat/v4l2_pix_fmts.h:274:1:</b> <font color="#CC0000"><b>error: </b></font>static assertion failed: &quot;V4L2_PIX_FMT_BGRA444 != v4l2_fourcc(\&apos;B\&apos;, \&apos;A\&apos;, \&apos;1\&apos;, \&apos;2\&apos;)&quot;
  274 | <font color="#CC0000"><b>static_assert</b></font>((V4L2_PIX_FMT_BGRA444) == (v4l2_fourcc(&apos;B&apos;, &apos;A&apos;, &apos;1&apos;, &apos;2&apos;)), &quot;V4L2_PIX_FMT_BGRA444 != v4l2_fourcc(&apos;B&apos;, &apos;A&apos;, &apos;1&apos;, &apos;2&apos;)&quot;);
      | <font color="#CC0000"><b>^~~~~~~~~~~~~</b></font>
make[2]: *** [Makefile:7280: strace-v4l2.o] Error 1
</pre>

<pre>$ uname -r; rpm -q libv4l-devel
5.2.9-200.fc30.x86_64
libv4l-devel-1.16.7-2.fc32.x86_64
</pre>

**Comment by esyr** [comment]
This UAPI change has been worked around in strace commit 60da39553ff92cf741bf7f54daff636bb28cbb3c.

**Comment by ldv-alt** [comment]
On Sat, Sep 21, 2019 at 05:20:22AM -0700, Tomasz Kłoczko wrote:
> <pre>gcc -DHAVE_CONFIG_H   -I./linux/x86_64 -I./linux/x86_64 -I./linux -I./linux -I. -I.      -Wall -Wempty-body -Wformat-security -Wignored-qualifiers -Wimplicit-fallthrough=5 -Winit-self -Wlogical-op -Wmissing-parameter-type -Wnested-externs -Wold-style-declaration -Wold-style-definition -Woverride-init -Wsign-compare -Wtype-limits -Wwrite-strings   -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -flto -c -o strace-v4l2.o `test -f &apos;v4l2.c&apos; || echo &apos;./&apos;`v4l2.c
> In file included from <b>./static_assert.h:11</b>,
>                  from <b>xlat/v4l2_pix_fmts.h:4</b>,
>                  from <b>v4l2.c:59</b>:
> <b>xlat/v4l2_pix_fmts.h:274:1:</b> <font color="#CC0000"><b>error: </b></font>static assertion failed: &quot;V4L2_PIX_FMT_BGRA444 != v4l2_fourcc(\&apos;B\&apos;, \&apos;A\&apos;, \&apos;1\&apos;, \&apos;2\&apos;)&quot;
>   274 | <font color="#CC0000"><b>static_assert</b></font>((V4L2_PIX_FMT_BGRA444) == (v4l2_fourcc(&apos;B&apos;, &apos;A&apos;, &apos;1&apos;, &apos;2&apos;)), &quot;V4L2_PIX_FMT_BGRA444 != v4l2_fourcc(&apos;B&apos;, &apos;A&apos;, &apos;1&apos;, &apos;2&apos;)&quot;);
>       | <font color="#CC0000"><b>^~~~~~~~~~~~~</b></font>
> make[2]: *** [Makefile:7280: strace-v4l2.o] Error 1
> </pre>

That was due to the kernel uapi regressions, worked around
by strace commit v5.2-23-g60da39553.

Anyway, it's too late to report that kind of bugs against 5.2
because 5.3 is going to be released in a few days.

**Comment by kloczek** [comment]
After apply 60da3955 patch still strace build fails:
<pre>make[2]: Entering directory &apos;/home/tkloczko/rpmbuild/BUILD/strace-5.2&apos;
gcc -DHAVE_CONFIG_H   -I./linux/x86_64 -I./linux/x86_64 -I./linux -I./linux -I. -I.      -Wall -Wempty-body -Wformat-security -Wignored-qualifiers -Wimplicit-fallthrough=5 -Winit-self -Wlogical-op -Wmissing-parameter-type -Wnested-externs -Wold-style-declaration -Wold-style-definition -Woverride-init -Wsign-compare -Wtype-limits -Wwrite-strings   -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -flto -c -o strace-v4l2.o `test -f &apos;v4l2.c&apos; || echo &apos;./&apos;`v4l2.c
In file included from <b>./static_assert.h:11</b>,
                 from <b>xlat/v4l2_pix_fmts.h:4</b>,
                 from <b>v4l2.c:59</b>:
<b>xlat/v4l2_pix_fmts.h:274:1:</b> <font color="#CC0000"><b>error: </b></font>static assertion failed: &quot;V4L2_PIX_FMT_BGRA444 != v4l2_fourcc(\&apos;B\&apos;, \&apos;A\&apos;, \&apos;1\&apos;, \&apos;2\&apos;)&quot;
  274 | <font color="#CC0000"><b>static_assert</b></font>((V4L2_PIX_FMT_BGRA444) == (v4l2_fourcc(&apos;B&apos;, &apos;A&apos;, &apos;1&apos;, &apos;2&apos;)), &quot;V4L2_PIX_FMT_BGRA444 != v4l2_fourcc(&apos;B&apos;, &apos;A&apos;, &apos;1&apos;, &apos;2&apos;)&quot;);
      | <font color="#CC0000"><b>^~~~~~~~~~~~~</b></font>
make[2]: *** [Makefile:7280: strace-v4l2.o] Error 1
m</pre>

**Comment by kloczek** [comment]
Closing.
5.3 builds correctly.

**Comment by Whissi** [comment]
> After apply 60da395 patch still strace build fails:

Keep in mind that the patch only modifies `xlat/v4l2_pix_fmts.in` file in git. In release tarball you are working with generated `xlat/v4l2_pix_fmts.h` file so you have to call `./xlat/gen.sh` first to regenerate header file based on changes applied to now patched `xlat/v4l2_pix_fmts.in`. Once header is regenerated, patched strace-5.2 works fine with linux-5.3.
