### ISSUE TITLE
5.3: test suite fails

### ISSUE THREAD

**Issue by kloczek** [strace/strace#111]
[test-suite.log](https://github.com/strace/strace/files/3659827/test-suite.log)

**Comment by ldv-alt** [comment]
On Thu, Sep 26, 2019 at 01:45:55PM -0700, Tomasz Kłoczko wrote:
> [test-suite.log](https://github.com/strace/strace/files/3659827/test-suite.log)

According to this log, it's "strace 5.2".
And, according to the log, it was improperly configured because
COPYRIGHT_YEAR is invalid or missing in config.h file generated by configure.

**Comment by ldv-alt** [comment]
Anyway, 5.4 was released last month.
