### ISSUE TITLE
Reasons behind project re-licensing

### ISSUE THREAD

**Issue by pavel-odintsov** [strace/strace#112]
Hello!

Thank you for your hard work on strace! That's my main debugging tool and I glad to have it.

May I kindly ask about reasons behind project re-licensing? I checked GitHub, GitLab and official maillist and did not find any mentions about it.

Can you explain it? I just curious and I have no issues with new or old licenses.

Thank you!

**Comment by lasczki-da** [comment]
+1. two questions:
1) who decided to re-license?
2) who approved?

**Comment by ldv-alt** [comment]
Please see https://lists.strace.io/pipermail/strace-devel/2018-December/008548.html

**Comment by pavel-odintsov** [comment]
Thank you for fast reply and clarification. That's clear for me now.
