### ISSUE TITLE
arm64 compile error: can not find definition of "struct user"

### ISSUE THREAD

**Issue by florencezhu** [strace/strace#113]
In process.c,  there is this "#define uoff(member)    offsetof(struct user, member)", while no definition of "struct user" is found,  does anybody know how to fix this issue?

**Comment by ldv-alt** [comment]
On Wed, Oct 23, 2019 at 08:01:14PM -0700, florencezhu wrote:
> In process.c,  there is this "#define uoff(member)    offsetof(struct user, member)", while no definition of "struct user" is found,  does anybody know how to fix this issue? 

This issue shall not arise at all.
How do you build strace?
What exactly is the command used to compile process.c?

**Comment by florencezhu** [comment]
1. ./configure --host=arm-linux CC=aarch64_eabi_gcc6.2.0_glibc2.24.0_fp/bin/aarch64-unknown-linux-gnueabi-gcc LD=aarch64_eabi_gcc6.2.0_glibc2.24.0_fp/bin/aarch64-unknown-linux-gnueabi-ld
2. make


> On Wed, Oct 23, 2019 at 08:01:14PM -0700, florencezhu wrote: In process.c, there is this "#define uoff(member) offsetof(struct user, member)", while no definition of "struct user" is found, does anybody know how to fix this issue?
> This issue shall not arise at all. How do you build strace? What exactly is the command used to compile process.c?

**Comment by ldv-alt** [comment]
On Thu, Oct 24, 2019 at 05:14:38AM -0700, florencezhu wrote:
> 1. ./configure --host=arm-linux CC=aarch64_eabi_gcc6.2.0_glibc2.24.0_fp/bin/aarch64-unknown-linux-gnueabi-gcc LD=aarch64_eabi_gcc6.2.0_glibc2.24.0_fp/bin/aarch64-unknown-linux-gnueabi-ld

If you build for aarch64, why do you specify --host=arm-linux option to configure?

**Comment by florencezhu** [comment]
Issue fixed, thanks a lot for your help!
