### ISSUE TITLE
5.4: build fails

### ISSUE THREAD

**Issue by kloczek** [strace/strace#115]
<pre>t.c
gcc -DHAVE_CONFIG_H   -I./linux/x86_64 -I./linux/x86_64 -I./linux -I./linux -I. -I.     -DIN_MPERS -DMPERS_IS_m32 -I./mpers-m32  -Wall -Wempty-body -Wformat-security -Wignored-qualifiers -Wimplicit-fallthrough=5 -Winit-self -Wlogical-op -Wmissing-parameter-type -Wnested-externs -Wold-style-declaration -Wold-style-definition -Woverride-init -Wsign-compare -Wtype-limits -Wwrite-strings   -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -flto=auto -flto-partition=none -c -o libmpers_m32_a-fetch_struct_stat64.o `test -f &apos;fetch_struct_stat64.c&apos; || echo &apos;./&apos;`fetch_struct_stat64.c
<b>fetch_struct_stat64.c:</b> In function &apos;<b>m32_fetch_struct_stat64</b>&apos;:
<b>fetch_struct_stat64.c:58:16:</b> <font color="#CC0000"><b>error: </b></font>storage size of &apos;<b>buf</b>&apos; isn&apos;t known
   58 |  struct_stat64 <font color="#CC0000"><b>buf</b></font>;
      |                <font color="#CC0000"><b>^~~</b></font>
<b>fetch_struct_stat64.c:58:16:</b> <font color="#75507B"><b>warning: </b></font>unused variable &apos;<b>buf</b>&apos; [<font color="#75507B"><b>-Wunused-variable</b></font>]
make[2]: *** [Makefile:3022: libmpers_m32_a-fetch_struct_stat64.o] Error 1
make[2]: Leaving directory &apos;/home/tkloczko/rpmbuild/BUILD/strace-5.4&apos;
make[1]: *** [Makefile:7542: all-recursive] Error 1
make[1]: Leaving directory &apos;/home/tkloczko/rpmbuild/BUILD/strace-5.4&apos;
</pre>

**Comment by ldv-alt** [comment]
This is a duplicate of https://github.com/strace/strace/issues/114.
