### ISSUE TITLE
strace-k test fails on aarch64

### ISSUE THREAD

**Issue by sharkcz** [strace/strace#12]
The strace-k test (from today's master) fails on aarch64 when built and run on Fedora 26 systems

strace-k.log on aarch64
```
../../strace: Can't initiate libunwind: Input/output error
getpid()                                = 16107
strace-k.test: failed test: ../../strace -e getpid -k ../stack-fcall failed with code 1
FAIL strace-k.test (exit status: 1)
```

Let me know if you need more information or access to an aarch64 system.

**Comment by sharkcz** [comment]
it's a result of "make check" when strace is built with libunwind, but as I read "-k" is an experimental option that's expected to work on x86 only

**Comment by sharkcz** [comment]
similar issue exists on ppc64 as #13

**Comment by esyr-rh** [comment]
Well, yep, there are plans to migrate to libdw for stack unwinding, but not much else. Meanwhile, it's better just to disable the option on non-x86 builds.

**Comment by sharkcz** [comment]
yup, I've already disabled the option for non-x86
