### ISSUE TITLE
Question about trace=%file and readdir?

### ISSUE THREAD

**Issue by cheako** [strace/strace#123]
Does %file include readdir and the like and if not why not?  There is no %dir AFAICT and looking at the source I see TD referenced for readdir but TD is linked to TRACE_DESC and there is no TRACE_DIR or anything.

Am I just confused or is the source wrong?

**Comment by esyr** [comment]
`%file` includes syscalls that take a file name as an argument. `%desc` includes syscalls that take an fd as an argument. `readdir(2)` takes fd as an arguments, hence it is included in `%desc` and not in `%file`.
