### ISSUE TITLE
Sudo effective user don't work with --seccomp-bpf

### ISSUE THREAD

**Issue by amerlyq** [strace/strace#126]
Literally. This works:
```bash
$ sudo strace -qqu $USER -e trace=execve -e signal=none -- sudo true

execve("/usr/bin/sudo", ["sudo", "true"], 0x7ffe1fc6b730 /* 13 vars */) = 0
```
And this not:
```bash
$ sudo strace --seccomp-bpf -fqqu $USER -e trace=execve -e signal=none -- sudo true

execve("/usr/bin/sudo", ["sudo", "true"], 0x7ffc693481d8 /* 13 vars */) = 0
sudo: effective uid is not 0, is /usr/bin/sudo on a file system with the 'nosuid' option set or an NFS file system without root privileges?

```
Is it temporary regression or `--seccomp-bpf` is fundamentally impossible for this usecase?

**Comment by ldv-alt** [comment]
On Tue, Feb 25, 2020 at 04:05:10AM -0800, Dmytro Kolomoiets wrote:
> Literally. This works:
> ```bash
> $ sudo strace -qqu $USER -e trace=execve -e signal=none -- sudo true
> 
> execve("/usr/bin/sudo", ["sudo", "true"], 0x7ffe1fc6b730 /* 13 vars */) = 0
> ```
> And this not:
> ```bash
> $ sudo strace --seccomp-bpf -fqqu $USER -e trace=execve -e signal=none -- sudo true
> 
> execve("/usr/bin/sudo", ["sudo", "true"], 0x7ffc693481d8 /* 13 vars */) = 0
> sudo: effective uid is not 0, is /usr/bin/sudo on a file system with the 'nosuid' option set or an NFS file system without root privileges?
> 
> ```
> Is it temporary regression or `--seccomp-bpf` is fundamentally impossible for this usecase?

This is a limitation of the current implementation which sets
PR_SET_NO_NEW_PRIVS unconditionally.  Apparently, in an unlikely case when
strace is privileged enough, there is no need to set PR_SET_NO_NEW_PRIVS.

**Comment by strace-devel-mailing-list** [comment]
On Tue, Feb 25, 2020 at 10:39:33PM +0000, Dmitry V. Levin wrote:
> On Tue, Feb 25, 2020 at 04:05:10AM -0800, Dmytro Kolomoiets wrote:
> > Literally. This works:
> > ```bash
> > $ sudo strace -qqu $USER -e trace=execve -e signal=none -- sudo true
> > 
> > execve("/usr/bin/sudo", ["sudo", "true"], 0x7ffe1fc6b730 /* 13 vars */) = 0
> > ```
> > And this not:
> > ```bash
> > $ sudo strace --seccomp-bpf -fqqu $USER -e trace=execve -e signal=none -- sudo true
> > 
> > execve("/usr/bin/sudo", ["sudo", "true"], 0x7ffc693481d8 /* 13 vars */) = 0
> > sudo: effective uid is not 0, is /usr/bin/sudo on a file system with the 'nosuid' option set or an NFS file system without root privileges?
> > 
> > ```
> > Is it temporary regression or `--seccomp-bpf` is fundamentally impossible for this usecase?
> 
> This is a limitation of the current implementation which sets
> PR_SET_NO_NEW_PRIVS unconditionally.  Apparently, in an unlikely case when
> strace is privileged enough, there is no need to set PR_SET_NO_NEW_PRIVS.

The only complication is that there seems to be no cheap way to find out
whether strace is privileged enough, and in most cases strace is not
privileged, so performing the check in all cases would unnecessarily
penalize the most widespread use case.

**Comment by amerlyq** [comment]
So... what the conclusion?
I often trace someone elses scripts which occasionally contain `sudo` and I have no way to remove it in all cases (after all `sudo` had a reason to be there).

Is there any workaround with privileges until aforementioned problem is fixed?
Something akin "running as grandchild and clearing cached pass phrase after reattaching tty" (despite it didn't work as such) ?

**Comment by strace-devel-mailing-list** [comment]
On Tue, Feb 25, 2020 at 10:39:33PM +0000, Dmitry V. Levin wrote:
> On Tue, Feb 25, 2020 at 04:05:10AM -0800, Dmytro Kolomoiets wrote:
> > Literally. This works:
> > ```bash
> > $ sudo strace -qqu $USER -e trace=execve -e signal=none -- sudo true
> > 
> > execve("/usr/bin/sudo", ["sudo", "true"], 0x7ffe1fc6b730 /* 13 vars */) = 0
> > ```
> > And this not:
> > ```bash
> > $ sudo strace --seccomp-bpf -fqqu $USER -e trace=execve -e signal=none -- sudo true
> > 
> > execve("/usr/bin/sudo", ["sudo", "true"], 0x7ffc693481d8 /* 13 vars */) = 0
> > sudo: effective uid is not 0, is /usr/bin/sudo on a file system with the 'nosuid' option set or an NFS file system without root privileges?
> > 
> > ```
> > Is it temporary regression or `--seccomp-bpf` is fundamentally impossible for this usecase?
> 
> This is a limitation of the current implementation which sets
> PR_SET_NO_NEW_PRIVS unconditionally.  Apparently, in an unlikely case when
> strace is privileged enough, there is no need to set PR_SET_NO_NEW_PRIVS.

Another complication is that strace installs the seccomp filter as late as
possible before execve, that is, strace -u $USER switches to $USER and
therefore drops privileges before installing the seccomp filter, which
means setting PR_SET_NO_NEW_PRIVS in case of strace -u seems to be
unavoidable.

**Comment by amerlyq** [comment]
Can we have an insecure option with BIG RED WARNING then, and allow these new privilages for any code under strace if user wants this ?

**Comment by ldv-alt** [comment]
On Tue, Feb 25, 2020 at 04:48:27PM -0800, Dmytro Kolomoiets wrote:
> Can we have an insecure option with BIG RED WARNING then, and allow these new privilages for any code under strace if user wants this ?

Unprivileged process is not allowed by the kernel to install a seccomp filter until PR_SET_NO_NEW_PRIVS is set.

**Comment by swarnimarun** [comment]
Why not add a flag that checks for privileges and mention it in the WARNING for above scenarios? (Seems viable enough to me.)

Would allow people to opt into the performance loss, for the sake of ease.
