### ISSUE TITLE
Build error against older Linux tree

### ISSUE THREAD

**Issue by jirislaby** [strace/strace#144]
#138 fixed the build for the new kernel, but headers from older kernels now cause build failures here:
```
[   57s] In file included from ./static_assert.h:11,
[   57s]                  from types/check-io_uring.c:3:
[   57s] types/check-io_uring.c:21:1: error: static assertion failed: "struct io_cqring_offsets size mismatch, please update the decoder or fix the kernel"
[   57s]    21 | static_assert(sizeof(struct io_cqring_offsets) <= offsetof(struct_io_cqring_offsets, resv2),
[   57s]       | ^~~~~~~~~~~~~
```
`offsetof` `resv2` is definitely smaller than `sizeof` the whole structure. So I think the assert is incorrect. Perhaps it should be using `offsetofend`:
```
static_assert(sizeof(struct io_cqring_offsets) <= offsetofend(struct_io_cqring_offsets, resv2),
```

**Comment by jirislaby** [comment]
But that will defeat the purpose of the test in cases where new members are added without reusing reserved fields. We perhaps should split the assertions into two:
- new kernels add members (offsetof)
- new kernels don't change the size and reuse reserved fields (offsetofend or no check)

**Comment by ldv-alt** [comment]
types/check-io_uring.c is a generated file, and its line 21 is currently differs from yours:
```
static_assert(sizeof(struct io_cqring_offsets) <= offsetof(struct_io_cqring_offsets, cqes),
```

Have you regenerated all files properly?

**Comment by jirislaby** [comment]
> Have you regenerated all files properly?

It seems I didn't. Thanks
