### ISSUE TITLE
Feature request: annotate sockets based on its destination

### ISSUE THREAD

**Issue by izh1979** [strace/strace#154]
Currently when you use options `-y` to annotate file names and socckets in the syscalls arguments it works good for the regular files (and makes life much easier! :+1:) but it could be improved for UNIX and network sockets. Currently you can see: something like:
```
accept4(3<socket:[15157]>, {sa_family=AF_INET, sin_port=htons(62958), sin_addr=inet_addr("1.2.3.4")}, [16], SOCK_CLOEXEC) = 29<socket:[91704707]>
open("/srv/www/i/moon.jpg", O_RDONLY|O_CLOEXEC) = 30</srv/www/test.jpg>
...
sendfile(29<socket:[91704707]>, 30</srv/www/test.jpg>, [0], 21952) = 21952
```
So it's not clear from the sendfile line, what is the 29-th file description (or socket's 91704707) destination is? It could be shown like this for better understanding:
`sendfile(29<socket:[91704707,AF_INET,1.2.3.4:62958]>, 30</srv/www/test.jpg>, [0], 21952) = 21952`

**Comment by izh1979** [comment]
Looks like `-yy` option already does it:
`sendfile(29<TCP:[1.2.3.4:80->5.6.7.8:63330]>, 30</srv/test.jpg>, [0], 21952) = 21952`

**Comment by ldv-alt** [comment]
On Mon, Sep 07, 2020 at 09:04:13AM -0700, Igor Zhbanov wrote:
> Currently when you use options `-y` to annotate file names and socckets in the syscalls arguments it works good for the regular files (and makes life much easier! :+1:) but it could be improved for UNIX and network sockets.

Have you tried -yy which is an alias to --decode-fds=all?
For details see the manual page.
