### ISSUE TITLE
Problem with compiling for Android aarch64 

### ISSUE THREAD

**Issue by LeeTiK** [strace/strace#159]
Good afternoon, I'm trying to compile strace for Android aarch64 

```
export CC = / usr / bin / aarch64-linux-gnu-gcc
export CFLAGS = "- O2 -static"
export LDFLAGS = "- static -pthread"

git clone https://github.com/strace/strace.git
cd strace
autoconf
./bootstrap

./configure --host = aarch64-linux --enable-mpers = no

make
```

And an error comes out: 

```
gcc -DHAVE_CONFIG_H   -I./linux/aarch64 -I./linux/aarch64 -I./linux -I./linux -I. -I.      -Wall -Wempty-body -Wformat-security -Wignored-qualifiers -Wimplicit-fallthrough=5 -Winit-self -Wlogical-op -Wmissing-parameter-type -Wnested-externs -Wold-style-declaration -Wold-style-definition -Woverride-init -Wsign-compare -Wtype-limits -Wwrite-strings -Werror   -g -O2 -MT libstrace_a-syscall.o -MD -MP -MF .deps/libstrace_a-syscall.Tpo -c -o libstrace_a-syscall.o test -f 'syscall.c' || echo './'syscall.c
In file included from syscall.c:1025:
./linux/aarch64/arch_regs.c:31:22: error: field ‘aarch64_r’ has incomplete type
   31 |  struct user_pt_regs aarch64_r;
      |                      ^~~~~
make[2]: * [Makefile:7182: libstrace_a-syscall.o] Ошибка 1
```

**Comment by DoranekoSystems** [comment]
This is a note of my trial and error on Ubuntu.
https://medium.com/@ichise_90070/how-to-cross-compile-strace-for-android-765956b1e9b6

**Comment by Zackptg5** [comment]
I got it to compile with ndk, here's my build script: https://github.com/Zackptg5/Cross-Compiled-Binaries-Android/tree/master/build_script

NDK has static_assert already defined but it's different than the one included in strace and so I have configure ignore ndk's. Also needed to specify arm64's ac_cv_prog_CC_FOR_M32 to arm clang

These fixes were needed starting with strace version 5.6. It works up to 5.10, then with 5.11, something changed and so I'm working on getting that to compile now. 5.5 didn't need any of the above
