### ISSUE TITLE
strace(64bit mode) can't support stack-traces when debug 32 bit tartget on X86

### ISSUE THREAD

**Issue by wangmu0579** [strace/strace#162]
I build v5.9 strace stack-trace works on X86_64 with 64 binary taget but can't  for 32 binary target.
How can I enable stack-trace for 32 binary target? Or any work-around for this?
Thanks.
![image](https://user-images.githubusercontent.com/24429869/95033011-3de06a80-06ef-11eb-8d44-8a367dff1999.png)
![image](https://user-images.githubusercontent.com/24429869/95032852-9f540980-06ee-11eb-86ed-5a6334a48106.png)

**Comment by wangmu0579** [comment]
![image](https://user-images.githubusercontent.com/24429869/95032937-ff4ab000-06ee-11eb-8980-632ee7161397.png)

**Comment by esyr** [comment]
On Mon, Oct 5, 2020 at 3:41 AM wangmu0579 <notifications@github.com> wrote:
> I build v5.9 strace but stack-trace works on X86_64 with 64 binary taget but can't for 32 binary target.
> How can I enable stack-trace for 32 binary target? Or any work-around for this?

libunwind is known to not work with binaries of non-strace-bitness;
you can try to use libdw-based unwinding (that is used in most
distributions where unwinding is enabled; `--with-libdw` configure
option). Also, please check that mpers support is indeed enabled
(`--enable-mpers=yes` configure option).  You can also refer to
`strace -V` output for these build options.

-- 
Eugene Syromyatnikov
mailto:evgsyr@gmail.com
xmpp:esyr@jabber.{ru|org}

**Comment by wangmu0579** [comment]
But I think strace already with libdw:
![image](https://user-images.githubusercontent.com/24429869/95086366-fee40080-0752-11eb-8783-f7dba0ed1469.png)

**Comment by esyr** [comment]
On Mon, Oct 5, 2020 at 3:38 PM wangmu0579 <notifications@github.com> wrote:
> But I think strace already with libdw:
Oh, you're right, the unwind support for non-native binaries was
disabled in commit v4.8-214-gf1d7311 and seems to be not enabled since
for libdw, that's an unfortunate omission.

**Comment by wangmu0579** [comment]
A little confused for your commet. So what should I do for enabling stack output to my application?

**Comment by esyr** [comment]
On Tue, Oct 6, 2020 at 4:12 PM wangmu0579 <notifications@github.com> wrote:
> A little confused for your commet. So what should I do for enabling stack output to my application?

This is not enabled in the master branch, as of now; meanwhile, it
would be great if you try out the esyr/enable-libdw-mpers branch[1]
where an attempt to enable stack unwinding for non-native binaries is
made.

[1] https://github.com/strace/strace/tree/esyr/enable-libdw-mpers
--
Eugene Syromyatnikov
mailto:evgsyr@gmail.com
xmpp:esyr@jabber.{ru|org}

**Comment by wangmu0579** [comment]
Seems branch enable-libdw-mpers do not have configure file which makes me block at how to compile the strace:
![image](https://user-images.githubusercontent.com/24429869/95296125-d1aa6600-08aa-11eb-8df7-9a91319505d2.png)
I tried to copy a unwind, there is also no call stack outputed:
![image](https://user-images.githubusercontent.com/24429869/95296501-775dd500-08ab-11eb-8988-7e2714f39439.png)

**Comment by wangmu0579** [comment]
https://github.com/strace/strace/tree/esyr/enable-libdw-mpers works for my application which output calllling stack.
Thanks esyr's help.
