### ISSUE TITLE
Should IPPROTO_MAX be updated?

### ISSUE THREAD

**Issue by Ikke** [strace/strace#164]
The latest version of musl updated `IPPROTO_MAX` in `/usr/include/netinet/in.h` to '263' after the addition of `IPPROTO_MPTCP`, which has a value of '262'.

Strace also [added IPPROTO_MPTCP](2c721018cc3351ee4518f4f57bbf5b646f96d533), but `IPPROTO_MAX` was not updated. This causes an assert to fail on Alpine Linux:

```
xlat/inet_protocols.h:242:1: error: static assertion failed: "IPPROTO_MAX != 256"
  242 | static_assert((IPPROTO_MAX) == (256), "IPPROTO_MAX != 256");
```

The question is, does it make sense to update `IPPROTO_MAX`, like musl did, or not. If it makes sense, but strace has not updated it due to compatibility with glibc, I can patch the strace definition on Alpine Linux for the time being to match. But if there is a good reason not to update it, musl will probably revert that change.

One hint I found in the [Linux source](https://github.com/torvalds/linux/blob/master/tools/include/uapi/linux/in.h#L83). There `IPPROTO_MAX` is defined after `IPPROTO_MPTCP` in the enum, indicating the value equals to '263'.

**Comment by ldv-alt** [comment]
https://lists.strace.io/pipermail/strace-devel/2020-October/010255.html
