### ISSUE TITLE
I was compiling strace:configure: error: failed to find libunwind-ptrace.h

### ISSUE THREAD

**Issue by Invincible-World** [strace/strace#165]
sudo apt install g++-arm-linux-gnueabihf g++-aarch64-linux-gnu autoconf make gawk libtool
git clone https://github.com/strace/strace.git
export CC=/usr/bin/aarch64-linux-gnu-gcc
export CFLAGS="-O2 -static"
export LDFLAGS="-static -pthread"
cd strace
./bootstrap
./configure --host=aarch64-linux --enable-mpers=no   --prefix=/usr --with-libunwind --with-libiberty

=====================out:
configure: error: failed to find libunwind-ptrace.h
==================================
How can I solve this problem? I have thought about it for a long time, but I still haven't solved it

**Comment by masatake** [comment]
You specified `--with-libunwind` as an argument of the ./configure invocation.
How about specifying `--without-libunwind` instead of it?

**Comment by Invincible-World** [comment]
> 您指定`--with-libunwind`了./configure调用作为参数。
> 如何指定`--without-libunwind`而不是呢？

After I do what you say, I can compile it successfully, but I still don't have the - K option after I put it on the Android phone

**Comment by dajima** [comment]
why this issue is closed? I have the same problem

**Comment by Nuc1eoN** [comment]
Same issue here.

**Comment by gluckzhang** [comment]
Similar issue here. Maybe #89 can be used for discussions instead.
