### ISSUE TITLE
cross compiling

### ISSUE THREAD

**Issue by peterius** [strace/strace#17]
Trying to cross compile with linaro aarch64 ... it's not exactly trivial.  I've had some issues doing this here and there, but usually the configure scripts pick up when the host and the build are different and it's not doing it here, the "cannot create executables"... etc..

Thanks.

**Comment by ldv-alt** [comment]
The description is too vague, could you elaborate, please?

**Comment by peterius** [comment]
Nevermind.  Sigh.  My environment has changed subtly.  But I got to say, cross-compiling is way way harder than it should be with everything.  There should just be some standard flag to specify a sysroot without chroot, and there just isn't.

**Comment by ldv-alt** [comment]
There are traditional CC, CPP, CFLAGS, CPPFLAGS, LDFLAGS to build target objects,
and CC_FOR_BUILD, CPP_FOR_BUILD, CFLAGS_FOR_BUILD, CPPFLAGS_FOR_BUILD, LDFLAGS_FOR_BUILD to build native objects (e.g. ioctlsort) required during build.
I suppose it works as expected for quite some time already.

**Comment by peterius** [comment]
No, the whole thing is a mess.  Some toolchains use LDFLAGS for some things and not others, you have to fix pass -rpath to the linker sometimes in weird places... every package and every configure has subtle differences.
