### ISSUE TITLE
output-separately appears misattribute syscalls

### ISSUE THREAD

**Issue by kkartaltepe** [strace/strace#176]
On strace 5.10 (archlinux packaging) when tracing a process that forks you can see parent syscalls in the child process trace file (and these syscalls will be missing from the parent trace file). Process launched with `strace -ff --output=strace.txt ./exe`

In my case the child process can be seen getting two different results from getpid().

```
getpid()                                = 616723
gettid()                                = 616724
```

Additional calls including those return fd's were also misattributed to the child process. On my machine this happens consistently and these calls are always misattributed after 10 or so tests. Let me know if there is any other information I might be be able to provide.

--- edit
And because this is not mentioned in the man page I assume it is a bug, if its known that this can happen a mention in the man page would be helpful.

**Comment by ldv-alt** [comment]
Note that in your example `getpid` != `gettid`, and there are no return fd's in the output, so it's hard to understand what are you talking about.
Please provide both the source code of your example and the output produced by strace.

**Comment by kkartaltepe** [comment]
The source code is available at https://github.com/obsproject/obs-studio/

Sorry I did not catch that the 2nd call was `gettid` thanks!

(Sorry new PIDs since this was from a new run). Discussion of FDs was just an example of where I found this. If an FD is created in the parent during this period you wont be able to find it in the parents log, it will only be in the child's log. I did not include the call to eventfd2() in this log but  for completeness, the following is the beginning of the log for `strace.txt.622549`

```
set_robust_list(0x7f1aea955920, 24)     = 0
rt_sigprocmask(SIG_SETMASK, [PIPE], NULL, 8) = 0
mmap(NULL, 134217728, PROT_NONE, MAP_PRIVATE|MAP_ANONYMOUS|MAP_NORESERVE, -1, 0) = 0x7f1ae2155000
munmap(0x7f1ae2155000, 32157696)        = 0
munmap(0x7f1ae8000000, 34951168)        = 0
mprotect(0x7f1ae4000000, 135168, PROT_READ|PROT_WRITE) = 0
futex(0x7f1aeda73068, FUTEX_WAKE_PRIVATE, 2147483647) = 0
eventfd2(0, EFD_CLOEXEC|EFD_NONBLOCK)   = 4
write(4, "\1\0\0\0\0\0\0\0", 8)         = 8
eventfd2(0, EFD_CLOEXEC|EFD_NONBLOCK)   = 5
write(5, "\1\0\0\0\0\0\0\0", 8)         = 8
futex(0x7f1aeda73068, FUTEX_WAKE_PRIVATE, 2147483647) = 0
futex(0x7f1aeda73264, FUTEX_WAKE_PRIVATE, 2147483647) = 0
getpid()                                = 622548
gettid()                                = 622549
prctl(PR_SET_NAME, "QXcbEventQueue")    = 0
poll([{fd=3, events=POLLIN}], 1, -1)    = 1 ([{fd=3, revents=POLLIN}])
recvmsg(3, {msg_name=NULL, msg_namelen=0, msg_iov=[{iov_base="\1\0\261\0\3\0\0\0!\0\0\0\1\0\0\1\377\377\377\377\0\0\0\0\0\1\2\0 \0\0\0"..., iov_len=4096}], msg_iovlen=1, msg_controllen=0, msg_flags=0}, 0) = 44
futex(0x7ffeeab064b8, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x55ee0a051638, FUTEX_WAKE_PRIVATE, 1) = 0
poll([{fd=3, events=POLLIN}], 1, -1)    = 1 ([{fd=3, revents=POLLIN}])
recvmsg(3, {msg_name=NULL, msg_namelen=0, msg_iov=[{iov_base="\1 \263\0\1\0\0\0!\0\0\0\0\0\0\0\1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"..., iov_len=4096}], msg_iovlen=1, msg_controllen=0, msg_flags=0}, 0) = 36
...
```

The relevant parts of the parent `strace.txt.622548` are that it contains writes to FD 5

```
...
clone(child_stack=0x7f1aea9549f0, flags=CLONE_VM|CLONE_FS|CLONE_FILES|CLONE_SIGHAND|CLONE_THREAD|CLONE_SYSVSEM|CLONE_SETTLS|CLONE_PARENT_SETTID|CLONE_CHILD_CLEARTID, parent_tid=[622549], tls=0x7f1aea955640, child_tidptr=0x7f1aea955910) = 622549 
...
// No calls that create FD 5.
...
write(5, "\1\0\0\0\0\0\0\0", 8)         = 8
```

With no corresponding call to open/eventfd2/pipe2 to create FD 5. And that `lsof -P 622548` identifies FD 5 as an eventfd. We can see that FD 5 is created by a call to `eventfd2` in the strace.txt.622549` and that pid 622549 is created before FD 5 is used in the parent process 622548.

**Comment by kkartaltepe** [comment]
Sorry and now that you mention they are the same process, its possible the fd is just being passed back. Feel free to close this out if you agree.

**Comment by ldv-alt** [comment]
> `strace.txt.622549`
...
> eventfd2(0, EFD_CLOEXEC|EFD_NONBLOCK)   = 4
> write(4, "\1\0\0\0\0\0\0\0", 8)         = 8
> eventfd2(0, EFD_CLOEXEC|EFD_NONBLOCK)   = 5
> write(5, "\1\0\0\0\0\0\0\0", 8)         = 8
...
> The relevant parts of the parent `strace.txt.622548` are that it contains writes to FD 5
> clone(child_stack=0x7f1aea9549f0, flags=CLONE_VM|CLONE_FS|CLONE_FILES|CLONE_SIGHAND|CLONE_THREAD|CLONE_SYSVSEM|CLONE_SETTLS|CLONE_PARENT_SETTID|CLONE_CHILD_CLEARTID, parent_tid=[622549], tls=0x7f1aea955640, child_tidptr=0x7f1aea955910) = 622549 
> ...
> // No calls that create FD 5.
> ...
> write(5, "\1\0\0\0\0\0\0\0", 8)         = 8

If  `CLONE_FILES`  is  set,  the  parent process and the child process share the same file descriptor table.

**Comment by kkartaltepe** [comment]
Thanks for checking. Again sorry for the noise.
