### ISSUE TITLE
Feature request: Allow process detaching after N syscalls captured

### ISSUE THREAD

**Issue by izh1979** [strace/strace#179]
It could be useful in automatic tests scenarious to attach to some daemon process, make some action, and detach after e.g. 1000 syscalls gets captured.

Also it could be useful to detach after 10 seconds.

**Comment by izh1979** [comment]
When atteching to several process the limit on the captured lines could be imposed on the total syscalls number for the simplicity.

**Comment by esyr** [comment]
Similar RFE: #139.
