### ISSUE TITLE
configure --enable-mpers=check fails to detect certain local misconfigurations

### ISSUE THREAD

**Issue by vi** [strace/strace#183]
Fails to build on Debian 11.

```
$ ./bootstrap && ./configure && make -j1
...
In file included from /usr/include/bits/errno.h:26,
                 from /usr/include/errno.h:28,
                 from ./defs.h:32,
                 from mpers-mx32/struct_blk_user_trace_setup.c:10:
/usr/include/linux/errno.h:1:10: fatal error: asm/errno.h: No such file or directory
```

**Comment by vapier** [comment]
your distro is broken.  install whatever packages are needed to unbreak it.  strace can't workaround this.

**Comment by vi** [comment]
Maybe that's because `gcc -mx32` does not work. Should strace's `./configure` check this?

Workaround for now: `./configure --enable-mpers=no`

**Comment by vapier** [comment]
did you try `./configure --enable-mpers=check` ?  that's meant to handle this situation.

that said, there is no reason for this breakage at the distro level.  the kernel headers are the same between x86, x86_64, and x32.

**Comment by vi** [comment]
`./configure --enable-mpers=check` still reproduces the error.

**Comment by ldv-alt** [comment]
https://lists.strace.io/pipermail/strace-devel/2021-March/010449.html

**Comment by ldv-alt** [comment]
Maybe ./configure --enable-mpers=check should detect this system misconfiguration.
