### ISSUE TITLE
tests: syslog test may hang waiting for SYSLOG_ACTION_READ completion

### ISSUE THREAD

**Issue by yangliping** [strace/strace#185]
`rpmbuild -ba strace.spec` failed with multiple test suite fails on CentOS 7.8. Attached is the log for test suite. Can anyone help on this?

Kernel: 3.10.0-1127.el7.x86_64
GCC: gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44)

[test-suite.log](https://github.com/strace/strace/files/6439474/test-suite.log)

**Comment by ldv-alt** [comment]
Each of these tests exceeded the time limit of 1500 seconds.

**Comment by yangliping** [comment]
While looking at one of these failed test, the syslog test.

```
+ read -r t prog_args
+ '[' syslog = syslog ']'
+ try_run_prog ../syslog
+ local rc
+ ../syslog
+ run_strace -qq -esignal=none -e/clock ../syslog
+ args='-qq -esignal=none -e/clock ../syslog'
+ ../../src/strace -o log -qq -esignal=none -e/clock ../syslog
CPU time limit exceeded
++ dump_log_and_fail_with 'time limit (1500) exceeded'
++ cat
++ fail_ 'time limit (1500) exceeded'
++ warn_ 'clock.gen.test: failed test: time limit (1500) exceeded'
++ printf '%s\n' 'clock.gen.test: failed test: time limit (1500) exceeded'
clock.gen.test: failed test: time limit (1500) exceeded
++ exit 1
FAIL clock.gen.test (exit status: 124)
```

I tried to run `syslog` program manually, and attach the process with strace. I found out that it stuck at `syslog(SYSLOG_ACTION_READ,`.

```
09:38:20.987716 syslog(SYSLOG_ACTION_READ, "", 0) = 0 <0.000011>
09:38:20.987764 write(1, "syslog(2 /* SYSLOG_ACTION_READ *"..., 46syslog(2 /* SYSLOG_ACTION_READ */, "", 0) = 0
) = 46 <0.000015>
09:38:20.987833 syslog(SYSLOG_ACTION_READ,
```

If I write some data to kernel's printk buffer, `syslog` will continue running and exit normally. How can I make it pass the test without manually write data to kernel buffer?

**Comment by esyr** [comment]
I'd like to note that running `rpmbuild -b*` outside an isolated environment and, moreover, under root is a very bad practice.
