### ISSUE TITLE
strace.io certificate has expired

### ISSUE THREAD

**Issue by cpackham** [strace/strace#186]
Not sure if this is the right place to report it but the strace.io certificate has expired. According to my browser it's not valid after Sat, 08 May 2021 04:00:22 GMT

**Comment by mator** [comment]
expired...
```
$ curl -v https://strace.io
* About to connect() to strace.io port 443 (#0)
*   Trying 194.107.17.35...
* Connected to strace.io (194.107.17.35) port 443 (#0)
* Initializing NSS with certpath: sql:/etc/pki/nssdb
*   CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
* Server certificate:
*       subject: CN=strace.io
*       start date: Apr 08 15:00:09 2021 GMT
*       expire date: Jul 07 15:00:09 2021 GMT
*       common name: strace.io
*       issuer: CN=R3,O=Let's Encrypt,C=US
* NSS error -8181 (SEC_ERROR_EXPIRED_CERTIFICATE)
* Peer's Certificate has expired.
* Closing connection 0
curl: (60) Peer's Certificate has expired.
```

@ldv-alt a task for a junior admin in ALT to setup a cron job to update letsencrypt (certbot) nginx SSL certs?

**Comment by ldv-alt** [comment]
On Thu, Jul 08, 2021 at 06:19:13AM -0700, Anatoly Pugachev wrote:
> @ldv-alt a task for a junior admin in ALT to setup a cron job to update letsencrypt (certbot) nginx SSL certs?

This site it maintained by volunteers.

**Comment by esyr** [comment]
It seems that the new certificate has been picked up successfully.
```
$ openssl s_client -showcerts -connect strace.io:443 2>/dev/null | openssl x509 -noout -dates
notBefore=Aug  6 15:00:12 2021 GMT
notAfter=Nov  4 15:00:10 2021 GMT
```
I'm closing the bug for now.
