### ISSUE TITLE
On aarch64, -Werror is enabled, but static function print_sigmask_addr_size from sigreturn.c is unused

### ISSUE THREAD

**Issue by justinkb** [strace/strace#188]
This breaks the build due to -Wunused-function turning into an error

**Comment by esyr** [comment]
This warning should't be triggered, `print_sigmask_addr_size` is inline. What is the build environment (compiler/libc)?

**Comment by ldv-alt** [comment]
Functions with `static inline` qualifiers shall not cause any -Wunused-function warnings.
If they do, then it's a compiler bug, please report it to the provider of your compiler and add a reference to the bug report here.

**Comment by justinkb** [comment]
Clang/glibc. I'll report it on llvm bugzilla. Thanks

**Comment by justinkb** [comment]
Found a year old stackoverflow thing about this on
https://stackoverflow.com/questions/59958785/unused-static-inline-functions-generate-warnings-with-clang
- definitely a clang issue. Can be closed :)
