### ISSUE TITLE
Issue in installing

### ISSUE THREAD

**Issue by anchitjain1234** [strace/strace#2]
I cloned the repo and then used these commands

1. ``libtoolize --force``
2. ``aclocal``
3. ``autoheader``
4. ``automake --force-missing --add-missing``
5. ``autoconf``
6. ``./configure``

Last command fails with output ``config.status: error: cannot find input file: `Makefile.in'``.

Also 4th command i.e. ``automake`` command also gives error ``automake: error: cannot open < xlat/Makemodule.am: No such file or directory``.

**Comment by ldv-alt** [comment]
README-hacking recommends to use ./bootstrap script instead.

**Comment by xuchuanyin** [comment]
In addition, after executing 'bootstrap', then execute 'configure' next.
