### ISSUE TITLE
linux/ipx.h was removed in 5.15

### ISSUE THREAD

**Issue by jirislaby** [strace/strace#201]
`linux/ipx.h` header was removed in https://github.com/torvalds/linux/commit/6c9b40844751ea30c72f7a2f92f4d704bc6b2927 and the strace's build now fails:
```
net-sockaddr.c:27:10: fatal error: linux/ipx.h: No such file or directory
```
There are 3 places where it is used:
```
$ git grep linux/ipx.h
src/net.c:# include <linux/ipx.h>
src/sockaddr.c:# include <linux/ipx.h>
tests/net-sockaddr.c:#include <linux/ipx.h>
```

**Comment by ldv-alt** [comment]
When Linux kernel breaks UAPI, it's up to them to pick up the pieces.
