### ISSUE TITLE
Generated tests are written into source tree

### ISSUE THREAD

**Issue by rossburton** [strace/strace#209]
If I do an out-of-tree build the generated test scripts (such as `tests/clock_nanosleep.gen.test`) are written into the source tree still, not the build tree.

**Comment by ldv-alt** [comment]
These scripts are generated by `bootstrap` before build, they belong to the source tree.

**Comment by ldv-alt** [comment]
There seems to be nothing to fix, closing.

**Comment by ldv-alt** [comment]
There seems to be nothing to fix, closing.

**Comment by ldv-alt** [comment]
There seems to be nothing to fix, closing.
