### ISSUE TITLE
Can I modify the arguments and return value for exactly arguments which I want to modify?

### ISSUE THREAD

**Issue by xyxdaily** [strace/strace#226]
openat(AT_FDCWD, "/system/lib64/libc.so", O_RDONLY|O_CLOEXEC) = 8
openat(AT_FDCWD, "/proc/self/maps", O_RDONLY|O_CLOEXEC) = 8

For example, for openat, I just want to modify the path which matches /proc/self/maps but donot modify other path.
`strace -e fault=openat:error=ENOENT` will affect all openat.

Could it be possible?

**Comment by ldv-alt** [comment]
Something like this soes the trick:
```
strace -P /proc/self/maps -eopenat -efault=openat:error=ENOENT
```
