### ISSUE TITLE
Unable to install strace with homebrew on M1 Mac

### ISSUE THREAD

**Issue by rewanthtammana** [strace/strace#233]
### Description

Unable to install `strace` on M1 Mac with ARM architecture with homebrew.

```
brew install strace
==> Fetching dependencies for strace: linux-headers@5.15
==> Fetching linux-headers@5.15
Error: Unable to build linux-headers@5.15 from source with HOMEBREW_INSTALL_FROM_API.
```

### Hardware info

Tested on MacOS Monterey with M1 chip.

**Comment by ldv-alt** [comment]
Please report this downstream.

**Comment by rewanthtammana** [comment]
Downstream? Can you please share the link? @ldv-alt

**Comment by ldv-alt** [comment]
Please direct distribution-specific questions to people who maintain the distribution, in this case it seems to be homebrew.
Here we have no information about their packages and have no way to help with them.

**Comment by rewanthtammana** [comment]
Sure, thanks!

**Comment by tedmiston** [comment]
@rewanthtammana Did you have any luck?

It seems to be broken for me on an Intel Mac too.

```shell
$ brew install strace
strace: Linux is required for this software.
linux-headers@5.15: Linux is required for this software.
Error: strace: Unsatisfied requirements failed this build.
```

Surely, it is possible to run strace on macOS, no?

**Comment by rewanthtammana** [comment]
@tedmiston I don't think strace will work as expected on mac OS. Even the description of https://github.com/strace/strace says, it's a utility for Linux.

I think dtrace, csrutil & dtruss might help with further debugging.

**Comment by tedmiston** [comment]
I was that note in the description, but figured most Linux compatible tools will work on any *nix.  But it seems you may be right here.

**Comment by rewanthtammana** [comment]
True. It depends on how the tools are built. If the tool is built to do operations at high level/userspace, then the middlewares are responsible to convert them to into system compatible formats at runtime. In this case, strace is built in C & looking for systems calls at kernel space & these change depending on the kernel builds. Hence, I'm assuming this won't work for MacOS as the underlying systems & build are different.
