### ISSUE TITLE
arch_prctl: non-mainline ARCH_CET_* constants are not recognized

### ISSUE THREAD

**Issue by hurufu** [strace/strace#240]
Thanks for this semi-magical tool!

Strace doesn't support value `0x3001` as the subfunction to `arch_prctl` system call, and prints `"ARCH_???"` instead. It looks like it is a new glibc feature that utilizes shadow stack: https://codebrowser.dev/glibc/glibc/sysdeps/unix/sysv/linux/x86/include/asm/prctl.h.html

Any chance it is going to be added in the near future?

**Comment by ldv-alt** [comment]
> Thanks for this semi-magical tool!

You are welcome!

> Strace doesn't support value `0x3001` as the subfunction to `arch_prctl` system call, and prints `"ARCH_???"` instead. It looks like it is a new glibc feature that utilizes shadow stack: https://codebrowser.dev/glibc/glibc/sysdeps/unix/sysv/linux/x86/include/asm/prctl.h.html

Note that these ARCH_CET_* constants are defined in a glibc header file, not a kernel one, and the glibc header file starts with the  following comment:

```
/* FIXME: CET arch_prctl bits should come from the kernel header files.
   This file should be removed if <asm/prctl.h> from the required kernel
   header files contains CET arch_prctl bits.  */
```

> Any chance it is going to be added in the near future?

Apparently, this CET feature has never been merged into mainline linux kernel.
There were numerous attempts during the last years, the latest seems to be
https://lore.kernel.org/lkml/20230218211433.26859-1-rick.p.edgecombe@intel.com/T/#u
where these constants have different names and numbers:

```
/* Don't use 0x3001-0x3004 because of old glibcs */

#define ARCH_SHSTK_ENABLE		0x5001
#define ARCH_SHSTK_DISABLE		0x5002
#define ARCH_SHSTK_LOCK			0x5003
```

Given that 0x3001..0x3004 constants are rejected by the kernel people already, I think strace shouldn't support them either.

**Comment by esyr** [comment]
Seems like the question has been resolved, closing the issue.
