### ISSUE TITLE
41GB files in tests output cause troubles for some tools

### ISSUE THREAD

**Issue by adrien-n** [strace/strace#247]
Hi,

After running "make check" in strace 6.1 and in strace git, the following:

    find -type f -size +1G -exec du -hs {} +

yields:

    0	./tests/clock.dir/stat.sample
    0	./tests/fstat.dir/stat.sample
    0	./tests/fstat-Xabbrev.dir/stat.sample
    0	./tests/fstat-Xraw.dir/stat.sample
    0	./tests/fstat-Xverbose.dir/stat.sample
    [...]

These very large files (66 files are 41GB and 2 files are 1.6GB) are an issue for tools that don't deal with sparse files efficiently, e.g. gnu tar by default (as used by autopkgtest for Debian/Ubuntu). For Ubuntu, I've updated the packaging to truncate files larger than 50MB down to 1MB (iirc) after tests are run (test artifacts are saved).

I've tried to understand what was going on but couldn't spot anything obvious and couldn't dive deep into the tests logic. I think this didn't happen with strace 5.19.

Of course, just as I'm creating this bug report, I'm now seeing that the code responsible for creating these files seems to be in "create_sample(const char *fname, const libc_off_t size)" in tests/xstatx.c and the size is governed by the SAMPLE_SIZE define.

It's possible nothing has changed in strace and it can be either something strace uses or something in the build/test infrastructure of Ubuntu or in Ubuntu in general. Nevertheless, a change in strace is the most likely at this point. Do you know if something related to that could have changed recently in strace? Why use 41GB? Is it because it's obviously over 4GB? Any idea or pointer?

Thanks.

**Comment by esyr** [comment]
For GNU tar, there is `-S`/`--sparse` option present.

**Comment by esyr** [comment]
Closing the issue, as it is not a strace's issue per se, but rather the specifics of handling of the produced sparse files by external utilities in external processes.
