### ISSUE TITLE
`./bootstrap` script frozen

### ISSUE THREAD

**Issue by nektro** [strace/strace#249]
trying to build strace from source my build gets stuck on https://github.com/strace/strace/blob/v6.2/src/generate_mpers_am.sh#L21

strace'ing the resulting `sed` reveals its stuck on a read of stdin

**Comment by nektro** [comment]
![image](https://user-images.githubusercontent.com/5464072/230809067-1de85e70-f798-4c78-b24a-574e8d0c6b53.png)

it appears `$list` is empty somehow

**Comment by nektro** [comment]
`xargs: command not found` was being written out and `set -e` was not set

**Comment by nektro** [comment]
hmm but https://github.com/strace/strace/blob/v6.2/src/generate_mpers_am.sh#L1 shows `#!/bin/sh -e` and `bash(1)` states:

> In addition to the single-character shell options documented in the description of the **set** builtin command, **bash** interprets the following options when it is invoked:

> errexit
> Same as -e.

**Comment by esyr** [comment]
> `xargs: command not found` was being written out and `set -e` was not set

It appears that your system doesn't have findutils installed.

**Comment by nektro** [comment]
> It appears that your system doesn't have findutils installed.

yes i discovered that and was able to work around this issue, but the issue i opened this for was that to discover that log message i had to do `./bootstrap && exit 1` rather than the script failing on its own and getting into a freeze/invalid state
