### ISSUE TITLE
Failing test case (sockopt-sol_netlink) in Yocto Project automated CI

### ISSUE THREAD

**Issue by rpurdie** [strace/strace#257]
I'm not sure why/when this started happening but we're seeing:

FAIL: sockopt-sol_netlink.gen
=============================

--- exp
+++ out
@@ -86,11 +86,11 @@
 setsockopt(3, SOL_NETLINK, NETLINK_LISTEN_ALL_NSID, 0x7f9e607ffc, -1) = -1 EINVAL (Invalid argument)
 setsockopt(3, SOL_NETLINK, NETLINK_LISTEN_ALL_NSID, 0x7f9e607ffc, 3) = 0
 setsockopt(3, SOL_NETLINK, NETLINK_LISTEN_ALL_NSID, 0x7f9e608000, 4) = -1 EFAULT (Bad address)
-getsockopt(3, SOL_NETLINK, NETLINK_LIST_MEMBERSHIPS, [0], [8]) = 0
+getsockopt(3, SOL_NETLINK, NETLINK_LIST_MEMBERSHIPS, [0], [4 => 8]) = 0
 getsockopt(3, SOL_NETLINK, NETLINK_LIST_MEMBERSHIPS, [0], [5 => 8]) = 0
 getsockopt(3, SOL_NETLINK, NETLINK_LIST_MEMBERSHIPS, NULL, [0 => 8]) = 0
 getsockopt(3, SOL_NETLINK, NETLINK_LIST_MEMBERSHIPS, [], [3 => 8]) = 0
-getsockopt(3, SOL_NETLINK, NETLINK_LIST_MEMBERSHIPS, 0x7f9e608000, [8]) = -1 EFAULT (Bad address)
+getsockopt(3, SOL_NETLINK, NETLINK_LIST_MEMBERSHIPS, 0x7f9e608000, [4]) = -1 EFAULT (Bad address)
 getsockopt(3, SOL_NETLINK, NETLINK_LIST_MEMBERSHIPS, 0x7f9e607ffc, 0x7f9e602000) = -1 EFAULT (Bad address)
 setsockopt(3, SOL_NETLINK, NETLINK_LIST_MEMBERSHIPS, [233811181], 4) = -1 ENOPROTOOPT (Protocol not available)
 setsockopt(3, SOL_NETLINK, NETLINK_LIST_MEMBERSHIPS, [233811181], 5) = -1 ENOPROTOOPT (Protocol not available)
sockopt-sol_netlink.gen.test: failed test: ../../src/strace -e trace=getsockopt,setsockopt ../sockopt-sol_netlink output mismatch
FAIL sockopt-sol_netlink.gen.test (exit status: 1)

**Comment by esyr** [comment]
On Fri, Jun 16, 2023 at 6:39 PM Richard Purdie ***@***.***> wrote:
>
> I'm not sure why/when this started happening but we're seeing:
>
> FAIL: sockopt-sol_netlink.gen
> [...]
> -getsockopt(3, SOL_NETLINK, NETLINK_LIST_MEMBERSHIPS, [0], [8]) = 0
> +getsockopt(3, SOL_NETLINK, NETLINK_LIST_MEMBERSHIPS, [0], [4 => 8]) = 0
> [...]
> -getsockopt(3, SOL_NETLINK, NETLINK_LIST_MEMBERSHIPS, 0x7f9e608000, [8]) = -1 EFAULT (Bad address)
> +getsockopt(3, SOL_NETLINK, NETLINK_LIST_MEMBERSHIPS, 0x7f9e608000, [4]) = -1 EFAULT (Bad address)
> [...]
> FAIL sockopt-sol_netlink.gen.test (exit status: 1)

Also reported at [1].

[1] https://lists.strace.io/pipermail/strace-devel/2023-June/011330.html

-- 
Eugene Syromyatnikov
***@***.***
***@***.***{ru|org}

**Comment by ldv-alt** [comment]
Fixed by f31c2f4494779e5c5f170ad10539bfc2dfafe967.
