### ISSUE TITLE
accept vs accept4 syscalls on 32 bit x86

### ISSUE THREAD

**Issue by rpurdie** [strace/strace#260]
Within Yocto Project we recently set 5.15 as our minimum kernel version. This changes the way glibc is built such that the accept() call changes to use the accept4 syscall behind the scenes. This causes various test failures in accept, net-yy-inet6, net-yy-inet and
net-y-unix. I'm not sure how this should be handled in strace?

As an example:

cat  net-yy-inet6.gen.log
--- exp
+++ out
@@ -5,7 +5,7 @@
 getsockopt(3<TCPv6:[[::1]:46887]>, SOL_TCP, TCP_MAXSEG, [536], [4]) = 0
 socket(AF_INET6, SOCK_STREAM, IPPROTO_IP) = 4<TCPv6:[17255]>
 connect(4<TCPv6:[17255]>, {sa_family=AF_INET6, sin6_port=htons(46887), sin6_flowinfo=htonl(0), inet_pton(AF_INET6, "::1", &sin6_addr), sin6_scope_id=0}, 28) = 0
-accept(3<TCPv6:[[::1]:46887]>, {sa_family=AF_INET6, sin6_port=htons(60152), sin6_flowinfo=htonl(0), inet_pton(AF_INET6, "::1", &sin6_addr), sin6_scope_id=0}, [28]) = 5<TCPv6:[[::1]:46887->[::1]:60152]>
+accept4(3<TCPv6:[[::1]:46887]>, {sa_family=AF_INET6, sin6_port=htons(60152), sin6_flowinfo=htonl(0), inet_pton(AF_INET6, "::1", &sin6_addr), sin6_scope_id=0}, [28], 0) = 5<TCPv6:[[::1]:46887->[::1]:60152]>
 getpeername(5<TCPv6:[[::1]:46887->[::1]:60152]>, {sa_family=AF_INET6, sin6_port=htons(60152), sin6_flowinfo=htonl(0), inet_pton(AF_INET6, "::1", &sin6_addr), sin6_scope_id=0}, [28]) = 0
 getpeername(4<TCPv6:[[::1]:60152->[::1]:46887]>, {sa_family=AF_INET6, sin6_port=htons(46887), sin6_flowinfo=htonl(0), inet_pton(AF_INET6, "::1", &sin6_addr), sin6_scope_id=0}, [28]) = 0
 setsockopt(4<TCPv6:[[::1]:60152->[::1]:46887]>, SOL_TCP, TCP_MAXSEG, [536], 4) = 0
net-yy-inet6.gen.test: failed test: ../../src/strace -a22 -yy -eclose,network ../net-yy-inet6 output mismatch
FAIL net-yy-inet6.gen.test (exit status: 1)

**Comment by ldv-alt** [comment]
On Thu, Jun 22, 2023 at 07:17:35AM -0700, Richard Purdie wrote:
> Within Yocto Project we recently set 5.15 as our minimum kernel version. This changes the way glibc is built such that the accept() call changes to use the accept4 syscall behind the scenes. This causes various test failures in accept, net-yy-inet6, net-yy-inet and
> net-y-unix. I'm not sure how this should be handled in strace?

I suppose those tests that do not test accept() specifically should be
migrated to accept4(), and the test of accept() needs some special
treatment to make sure it doesn't use the glibc wrapper and invokes
either __NR_accept or __NR_socketcall(SYS_ACCEPT).
