### ISSUE TITLE
linux-6.5 compatible release request

### ISSUE THREAD

**Issue by trofi** [strace/strace#266]
When I updated `linux-headers` upto latest `6.5` in `nixpkgs` I noticed that recent `strace` is still `6.4` and it tails to build as https://github.com/NixOS/nixpkgs/pull/252587#issuecomment-1702732344 

```
io_uring.c: In function 'print_io_sqring_offsets':
io_uring.c:48:16: error: 'const struct io_sqring_offsets' has no member named 'resv2'; did you mean 'resv1'?
   48 |         if (p->resv2) {
      |                ^~~~~
      |                resv1
```

The `strace` from `git` builds fine. The fixes are probably in e0da3633669fcb829dd8d902d15443a755bd10fb and others.

Worth cutting a new `strace` release to trail `linux` release?

Thanks!

**Comment by ldv-alt** [comment]
Sure, strace v5.5 is expected to be released this week.

**Comment by ldv-alt** [comment]
https://github.com/strace/strace/releases/tag/v6.5
