### ISSUE TITLE
feature request: configurable stacktrace depth limit

### ISSUE THREAD

**Issue by itrofimow** [strace/strace#271]
Hi!

Would it be possible to make this limit
https://github.com/strace/strace/blob/dc88a084ebbabde577c3d23982550de998e50ce7/src/unwind-libunwind.c#L134-L135
configurable via command-line parameters?

-----------
Context: i was debugging a complicated chain of processes calling each other, where some of the processes were dying due to a segfault.
I was able to trace the issue down to an endless recursion and inevitable StackOverflow via `strace -f -e 'trace=!all' -k`, however because of the hardcoded depth limit i couldn't find the problematic caller which initiated the recursion, and ended up patching strace for that.

**Comment by ldv-alt** [comment]
@masatake, do you think we could add an option to control this limit?

**Comment by masatake** [comment]
@ldv-alt Yes, I think. I will work on this item.

**Comment by masatake** [comment]
I will work on this item after finishing #268.
@ldv-alt How should the option be? --stack-limit=N ?

**Comment by ldv-alt** [comment]
I don't have a strong preference for the name.

**Comment by itrofimow** [comment]
@masatake i would be glad giving this a try myself, taking your work at https://github.com/strace/strace/pull/268 as a reference on how parameters should be added; other parts of the implementation seem straightforward. 

Do you mind?

**Comment by masatake** [comment]
@itrofimow Please, go ahead!

**Comment by itrofimow** [comment]
Resolved by https://github.com/strace/strace/pull/272
