### ISSUE TITLE
Add option to always show PID

### ISSUE THREAD

**Issue by JakobDev** [strace/strace#278]
I'm currently trying to write a script which shows which file is edit by a process and it's childs. You can filter the output by the process. I'm using `strace -fyy -e trace=%file --decode-pids=comm <command>` and parse the output.  But there's a little problem: If a syscall is made by a child process, strace prints `[pid  {pid}<{name}>] {rest of line}`, but if the syscall is made by the process started by strace, this part if missing, what makes this more complex to parse. It would be nice to have a argument to make the output always starts with  `[pid  {pid}<{name}>] {rest of line}`.

**Comment by esyr** [comment]
You can trick `strace` into doing so by setting the `--output` option, `strace -fo /dev/stderr COMMAND`, for example.

**Comment by JakobDev** [comment]
That seems to solve it. Thanks! But I think it would be better to have a official option than to rely on a workaround, so I keep this Issue open.

**Comment by sheharyaar** [comment]
Hi @ldv-alt , I would like to work on this feature, can you please assign me this ?

**Comment by ldv-alt** [comment]
> Hi @ldv-alt , I would like to work on this feature, can you please assign me this ?

Feel free to work on this if you like.
