### ISSUE TITLE
strace help page do not EXPLICITY says that output to filename must be set exactly after strace, and not at the end of the commande 

### ISSUE THREAD

**Issue by estatistics** [strace/strace#284]
strace help page do not EXPLICITY says that output to filename must be set exactly after strace, and not at the end of the command.

If you search in stackoverflow / superusers, many have problems to understand that --output=log.txt must be set exactly AFTER strace and not at the end of the full command in terminal

Right: strace --output=log.txt ./program
Wrong (no output file): strace  ./program --output=log.txt

Even my self now more than 15 minutes tried to understand why a log file was not produced experimenting with many combinations! Please edit your man page to be clearer on that topic.

**Comment by estatistics** [comment]
eg. https://man7.org/linux/man-pages/man1/strace.1.html

**Comment by esyr** [comment]
The `SYNOPSIS` section of the manual page (also present in the provided link) explicitly describes the `strace`'s invocation format syntax, where all the options explicitly precede `command` and its arguments.

**Comment by estatistics** [comment]
Do you think  this is a CLEAR example of how to run strace? 

```
      strace [-ACdffhikqqrtttTvVwxxyyYzZ] [-a column] [-b execve]
              [-e expr]... [-I n] [-o file] [-O overhead] [-p pid]...
              [-P path]... [-s strsize] [-S sortby] [-U columns]
              [-X format] [--seccomp-bpf] [--syscall-limit limit]
              [--secontext[=format]] [--tips[=format]] { -p pid | [-DDD]
              [-E var[=val]]... [-u username] command [args] }
```
compare to this:
`strace options  ./program options` 

And what means command? It is very arguable what that means. A command can be any character typed somewhere (valid or invalid). program / app is much clearer i think!

**Comment by ldv-alt** [comment]
`command` is the accepted terminology.
For example, this is env(1) synopsis:
`env [OPTION]... [-] [NAME=VALUE]... [COMMAND [ARG]...]`

**Comment by estatistics** [comment]
ok, its your right to create confusion. Why you dont ask people to vote, make a survey about your friends and ask them. Show them only the help page and ask them to debug a command (program).
