### ISSUE TITLE
strace fails to build it's tests on arm-linux-gnueabihf with 64bit time_t

### ISSUE THREAD

**Issue by doko42** [strace/strace#296]
strace 6.8 fails to build it's tests on arm-linux-gnueabihf with 64bit time_t:

make[5]: Entering directory '/<<PKGBUILDDIR>>/build/tests'
depbase=`echo _newselect.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
gcc -DHAVE_CONFIG_H    -I. -I../src/linux/arm -I../../src/linux/arm -I../src/linux/generic -I../../src/linux/generic -I../src -I../../src -I../../bundled/linux/arch/arm/include/uapi -I../../bundled/linux/include/uapi -DSTRACE_SIZEOF_KERNEL_LONG_T=4 -DTESTS_SIZEOF_KERNEL_LONG_T=4 -DSTRACE_SIZEOF_LONG=4 -DTESTS_SIZEOF_LONG=4  -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -D_TIME_BITS=64 -Wdate-time -D_FORTIFY_SOURCE=3 -I../bundled/linux/arch/arm/include/uapi -I../bundled/linux/include/uapi -Wall -Wextra -Wno-missing-field-initializers -Wno-unused-parameter -Wdate-time -Wformat-security -Wimplicit-fallthrough=5 -Winit-self -Wlogical-op -Wmissing-prototypes -Wnested-externs -Wold-style-definition -Wtrampolines -Wundef -Wwrite-strings -Werror -g -O2 -Werror=implicit-function-declaration -ffile-prefix-map=/<<PKGBUILDDIR>>=. -fstack-protector-strong -Wformat -Werror=format-security -fno-stack-clash-protection -fdebug-prefix-map=/<<PKGBUILDDIR>>=/usr/src/strace-6.8-0ubuntu1 -Wall -g -O2 -MT _newselect.o -MD -MP -MF $depbase.Tpo -c -o _newselect.o ../../tests/_newselect.c &&\
mv -f $depbase.Tpo $depbase.Po
mv -f .deps/libstrace_a-xmalloc.Tpo .deps/libstrace_a-xmalloc.Po
In file included from ../../tests/_newselect.c:16:
../../tests/xselect.c: In function ‘main’:
gcc -DHAVE_CONFIG_H   -I./linux/arm -I../../src/linux/arm -I./linux/generic -I../../src/linux/generic -I. -I../../src -I../../bundled/linux/arch/arm/include/uapi -I../../bundled/linux/include/uapi -DIN_STRACE=1      -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -D_TIME_BITS=64 -Wdate-time -D_FORTIFY_SOURCE=3 -I../bundled/linux/arch/arm/include/uapi -I../bundled/linux/include/uapi -Wall -Wextra -Wno-missing-field-initializers -Wno-unused-parameter -Wdate-time -Wformat-security -Wimplicit-fallthrough=5 -Winit-self -Wlogical-op -Wmissing-prototypes -Wnested-externs -Wold-style-definition -Wtrampolines -Wundef -Wwrite-strings -Werror   -g -O2 -Werror=implicit-function-declaration -ffile-prefix-map=/<<PKGBUILDDIR>>=. -fstack-protector-strong -Wformat -Werror=format-security -fno-stack-clash-protection -fdebug-prefix-map=/<<PKGBUILDDIR>>=/usr/src/strace-6.8-0ubuntu1 -Wall -g -O2 -MT libstrace_a-bpf_attr_check.o -MD -MP -MF .deps/libstrace_a-bpf_attr_check.Tpo -c -o libstrace_a-bpf_attr_check.o `test -f 'bpf_attr_check.c' || echo '../../src/'`bpf_attr_check.c
../../tests/xselect.c:216:24: error: overflow in conversion from ‘long long int’ to ‘kernel_long_t’ {aka ‘long int’} changes value from ‘-3819351491602432273’ to ‘-559038737’ [-Werror=overflow]
  216 |         tv_in.tv_sec = (time_t) 0xcafef00ddeadbeefLL;
      |                        ^

**Comment by cpaelzer** [comment]
Oh, I didn't realize you opened an issue here.

The fix for that was submitted in https://lists.strace.io/pipermail/strace-devel/2024-April/011415.html I can as well provide that as a PR here but the strace.io page said mailing list. Let me know if you prefer it here.
