### ISSUE TITLE
strace -e fault=xxx:errno=0 would  be really handy

### ISSUE THREAD

**Issue by ohsix** [strace/strace#3]
currently values are clamped to 1..4095

aside from being an interesting type of fault when you expect something to fail, it is also useful for 'disabling' a syscall, say: unlink. if you have some 'interesting' program or something you want to keep its files around for inspection when they do open/write/subprogram uses file/unlink

thanks

**Comment by Naam** [comment]
Hi @ohsix, please note GitHub is only used as a mirror.
Can you use the [mailing list](https://sourceforge.net/p/strace/mailman/) instead?

Thanks,
