### ISSUE TITLE
test failures on 32bit on v6.8

### ISSUE THREAD

**Issue by yuzibo** [strace/strace#301]
Hi,
After uploading v6.8, we got some test regressions on 32 bit systems, see [#1070853](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1070853).

but I do not have 32 bit arm hardware by hand, so more info I can not offer now. But please point doing what can help this and I can think of some ways.

**Comment by ldv-alt** [comment]
According to the logs, strace was configured with libunwind, and all `strace -k` tests failed.
Could you try building strace with libdw instead of libunwind?

**Comment by yuzibo** [comment]
> According to the logs, strace was configured with libunwind, and all strace -k tests failed.
Ah, the change was by me to response to the [MR](https://salsa.debian.org/debian/strace/-/merge_requests/3)

>Could you try building strace with libdw instead of libunwind?

Okay, I will try it. but given it was built on other architectures, can I only build it with `libdw` on arm* architectures?

**Comment by ldv-alt** [comment]
I'd recommend libdw instead of libunwind on all architectures where libdw is available.
Meanwhile, strace v6.9 has been released.

**Comment by yuzibo** [comment]
I would like to close the issue given the 6.8 is too old.
