### ISSUE TITLE
PID namespace translation

### ISSUE THREAD

**Issue by ghost** [strace/strace#31]
https://bugzilla.redhat.com/show_bug.cgi?id=1035433

**Comment by abhishekcs10** [comment]
I want to work on this issue. Please clarify syntax of **printxval** function.

**Comment by lineprinter** [comment]
@abhishekcs10 All consulting is usually done through the mailing list: https://lists.sourceforge.net/lists/listinfo/strace-devel
Could you ask your question there instead?

**Comment by ldv-alt** [comment]
Implemented since commit v5.9~52 (--pidns-translation option).
