### ISSUE TITLE
Findings by static analyzers in Fedora 41

### ISSUE THREAD

**Issue by siteshwar** [strace/strace#310]
A recent scan triggered through Packit generated list of findings in Fedora 41. They can be seen on the [results page](
https://openscanhub.fedoraproject.org/task/2492/log/strace-v6.10-1.20240731131624203964.master.13.gab728c1fc/scan-results.html). A more verbose logs can be seen in [scan-results-verbose.txt](https://github.com/user-attachments/files/16443398/scan-results-verbose.txt). Do these findings contain any real bug?

**Comment by ldv-alt** [comment]
Looks like all of them are false positives:
- gcc -fanalyzer is not insightful enough yet to see that the value returned by `entering(tcp)` doesn't change within the function being analyzed;
- cppcheck is just issuing bogus error diagnostics, also the verbose report ends with the following:
```
Error: CPPCHECK_WARNING:
strace-v6.10-build/strace-6.10.0.13.ab72/src/syscall.c: internal warning: child 15577 terminated by signal 11
```

**Comment by siteshwar** [comment]
> Looks like all of them are false positives:

In that case, you can close this issue. In the future, keep an eye on the [osh-diff-scan](https://github.com/strace/strace/pull/252/checks?check_run_id=28162776622) jobs submitted through Packit. Thanks!
