### ISSUE TITLE
"strace --summary-only sleep 10" shows %time 0.00 for all syscalls

### ISSUE THREAD

**Issue by dstromberg** [strace/strace#317]
Hello.

I'm thinking either I'm misunderstanding the meaning of the --summary-only report, or strace is having a bad time of it.

I'm seeing:
$ strace --summary-only /bin/sleep 10
below cmd output started 2024 Fri Sep 27 02:22:33 PM PDT
% time     seconds  usecs/call     calls    errors syscall
------ ----------- ----------- --------- --------- ----------------
  0.00    0.000000           0         1           read
  0.00    0.000000           0         4           close
  0.00    0.000000           0         8           mmap
  0.00    0.000000           0         4           mprotect
  0.00    0.000000           0         1           munmap
  0.00    0.000000           0         3           brk
  0.00    0.000000           0         4           pread64
  0.00    0.000000           0         1         1 access
  0.00    0.000000           0         1           execve
  0.00    0.000000           0         2         1 arch_prctl
  0.00    0.000000           0         1           set_tid_address
  0.00    0.000000           0         1           clock_nanosleep
  0.00    0.000000           0         2           openat
  0.00    0.000000           0         2           newfstatat
  0.00    0.000000           0         1           set_robust_list
  0.00    0.000000           0         1           prlimit64
  0.00    0.000000           0         1           getrandom
  0.00    0.000000           0         1           rseq
------ ----------- ----------- --------- --------- ----------------
100.00    0.000000           0        39         2 total
above cmd output done    2024 Fri Sep 27 02:22:43 PM PDT

I would've expected clock_nanosleep() to be 10 seconds.

What am I missing?

I'm using: strace -- version 5.16
...on a Linux system.

Thanks for the great tool!  It's one of the main things I miss when I use a Mac.

PS: I started suspecting something was misunderstood or broken when a test program reported strange results with strace --summary-only too.

**Comment by masatake** [comment]
Strace reports, "How much time does the CPU spend processing system calls?"
About clock_nanosleep, there is a little area where a CPU works.

**Comment by esyr** [comment]
You can try o use `-w`/`--summary-wall-clock` to see your expected `clock_nanosleep()` time:
```
pts/6, esyr@nurgle: ~ % strace --summary-only --summary-wall-clock /bin/sleep 1 
% time     seconds  usecs/call     calls    errors syscall
------ ----------- ----------- --------- --------- ----------------
 99.83    1.000418     1000418         1           clock_nanosleep
  0.05    0.000508         508         1           execve
  0.03    0.000297          59         5           close
  0.03    0.000258          28         9           mmap
  0.02    0.000170          56         3           brk
  0.01    0.000122          40         3           openat
  0.01    0.000078          25         3           mprotect
  0.01    0.000058          19         3           fstat
  0.00    0.000045          44         1           munmap
  0.00    0.000038          37         1         1 access
  0.00    0.000037          18         2           pread64
  0.00    0.000024          24         1           getrandom
  0.00    0.000021          21         1           read
  0.00    0.000019          18         1           prlimit64
  0.00    0.000018          18         1           arch_prctl
  0.00    0.000018          18         1           set_tid_address
  0.00    0.000018          18         1           rseq
  0.00    0.000017          17         1           set_robust_list
------ ----------- ----------- --------- --------- ----------------
100.00    1.002164       25696        39         1 total
```
But this question, I guess, also taps into the fact that unfortunately kernel doesn't provide good precision for CPU time accounting on most architectures (that's why you're seeing all zeroes, which is not entirely correct), it's HZ-coarse almost everywhere except where `VIRT_CPU_ACCOUNTING_NATIVE` is enabled, so, powerpc and s390, cf.:
```
pts/6, esyr@nurgle: ~ % uname -a
Linux nurgle 5.10.0-6-amd64 #1 SMP Debian 5.10.28-1 (2021-04-09) x86_64 GNU/Linux
pts/6, esyr@nurgle: ~ % strace --summary-only /bin/sleep 1
% time     seconds  usecs/call     calls    errors syscall
------ ----------- ----------- --------- --------- ----------------
  0.00    0.000000           0         1           read
  0.00    0.000000           0         5           close
  0.00    0.000000           0         3           fstat
  0.00    0.000000           0         9           mmap
  0.00    0.000000           0         3           mprotect
  0.00    0.000000           0         1           munmap
  0.00    0.000000           0         3           brk
  0.00    0.000000           0         2           pread64
  0.00    0.000000           0         1         1 access
  0.00    0.000000           0         1           execve
  0.00    0.000000           0         1           arch_prctl
  0.00    0.000000           0         1           set_tid_address
  0.00    0.000000           0         1           clock_nanosleep
  0.00    0.000000           0         3           openat
  0.00    0.000000           0         1           set_robust_list
  0.00    0.000000           0         1           prlimit64
  0.00    0.000000           0         1           getrandom
  0.00    0.000000           0         1           rseq
------ ----------- ----------- --------- --------- ----------------
100.00    0.000000           0        39         1 total
```
```
esyr@talos:~$ uname -a
Linux talos 5.15.0-3-powerpc64le #1 SMP Debian 5.15.15-2 (2022-01-30) ppc64le GNU/Linux
esyr@talos:~$ strace -c /bin/sleep 1
% time     seconds  usecs/call     calls    errors syscall
------ ----------- ----------- --------- --------- ----------------
 23.33    0.000028           9         3           mprotect
 17.50    0.000021           4         5           close
 11.67    0.000014           4         3           brk
 10.83    0.000013          13         1           munmap
 10.00    0.000012           4         3           openat
 10.00    0.000012           4         3           newfstatat
  8.33    0.000010           2         4           mmap
  8.33    0.000010          10         1           clock_nanosleep
  0.00    0.000000           0         1           read
  0.00    0.000000           0         1           execve
  0.00    0.000000           0         1         1 access
------ ----------- ----------- --------- --------- ----------------
100.00    0.000120           4        26         1 total
```

**Comment by masatake** [comment]
I didn't know `-w/--summary-wall-clock`. I learned.

**Comment by esyr** [comment]
I'm closing this issue, at the original question has been addressed, per my understanding, and seemingly there's not much strace itself can do to improve the situation with the CPU accounting precision.
