### ISSUE TITLE
strace hangs on ia64 (fresh kernel)

### ISSUE THREAD

**Issue by trofi** [strace/strace#33]
It's a version of downstream bug: https://bugs.gentoo.org/518130

I've recently upgraded kernel on ia64 machine
from 3.14.14-gentoo (GCC: Gentoo 4.9.3 p1.2, pie-0.6.3)
to 4.9.72-gentoo (GCC: Gentoo 6.4.0-r1 p1.3)

and strace started hanging up there. It might be a state decoding problem in `strace` or a bug in kernel.

```
slyfox@guppy 0:0 ~ $ strace -d ls
strace: ptrace_setoptions = 0x51
strace: new tcb for pid 10345, active tcbs:1
strace: [wait(0x80137f) = 10345] WIFSTOPPED,sig=SIGSTOP,EVENT_STOP (128)
strace: pid 10345 has TCB_STARTUP, initializing it
strace: [wait(0x80057f) = 10345] WIFSTOPPED,sig=SIGTRAP,EVENT_STOP (128)
strace: [wait(0x00127f) = 10345] WIFSTOPPED,sig=SIGCONT
strace: [wait(0x00857f) = 10345] WIFSTOPPED,sig=133
????
```

I can reproduce the strace hangun in `ski` (ia64 emulator on current upstream kernel). When added a few `printk()` statements in kernel I found the place where 133 code comes from: http://elixir.free-electrons.com/linux/latest/source/include/linux/tracehook.h#L66

```c
static inline int ptrace_report_syscall(struct pt_regs *regs)
{
	int ptrace = current->ptrace;

	if (!(ptrace & PT_PTRACED))
		return 0;

	ptrace_notify(SIGTRAP | ((ptrace & PT_TRACESYSGOOD) ? 0x80 : 0));
...
```
which looks like normal mode of operation. But looks like `strace` does not recognize it and outputs raw `sig=133` message. There is a possibility of kernel being miscompiled by new compiler as gdb hangs the same way.

x86_64 also does not decode that `sig=133`.

**Comment by ldv-alt** [comment]
I've added some debug printing to get_regs:
$ ./strace -d /
./strace: ptrace_setoptions = 0x51
./strace: new tcb for pid 11080, active tcbs:1
./strace: [wait(0x80137f) = 11080] WIFSTOPPED,sig=SIGSTOP,EVENT_STOP (128)
./strace: pid 11080 has TCB_STARTUP, initializing it
./strace: [wait(0x80057f) = 11080] WIFSTOPPED,sig=SIGTRAP,EVENT_STOP (128)
./strace: [wait(0x00127f) = 11080] WIFSTOPPED,sig=SIGCONT
./strace: [wait(0x00857f) = 11080] WIFSTOPPED,sig=133
./strace: get_regs: get_regs_error: Input/output error
????

Looks like ptrace(PTRACE_GETREGS) always fails with EIO on this new kernel.

**Comment by ldv-alt** [comment]
133 == SIGTRAP | 0x80, strace doesn't decode it in -d output, most probably because the main audience of strace -d is familiar with it.

**Comment by trofi** [comment]
That's very helpful! Thank you!

Looking at kernel side of unwinder (used to read registers).

**Comment by trofi** [comment]
Confirmed it was `ptrace(PTRACE_GETREGS)` bug. With https://github.com/0day-ci/linux/commit/97d0c5921c06af75f176d46ba1a56a0dec914808 applied ia64 machine can run strace without problems. Thanks again!

**Comment by ldv-alt** [comment]
The kernel seems to be fixed now, with
Linux guppy 4.9.72-gentoo #3 SMP Mon Feb 5 23:10:14 UTC 2018 ia64 Dual-Core Intel(R) Itanium(R) Processor 9040 GenuineIntel GNU/Linux
strace passes tests again, thanks!
