### ISSUE TITLE
Release tarballs do not provide a configure script anymore

### ISSUE THREAD

**Issue by skarnet** [strace/strace#4]
Hello,
Tagged releases are supposed to be self-sufficient with respect to build tools, i.e. they shouldn't require the full autotools suite. But recent releases of strace (at least 4.14 and 4.15) do not provide a configure script.

 Could I get a tagged release with a configure script, please? And, ideally, could the habit of bundling a configure script with tagged releases be brought back?

Thanks.

**Comment by ldv-alt** [comment]
$ tar -tvf strace-4.14.tar.xz | grep configure
-rw-r--r-- 0/0           21468 2016-09-28 06:00 strace-4.14/configure.ac
-rwxr-xr-x 0/0          353258 2016-10-04 22:13 strace-4.14/configure
$ tar -tvf strace-4.15.tar.xz | grep configure
-rw-r--r-- 0/0           21751 2016-12-07 13:59 strace-4.15/configure.ac
-rwxr-xr-x 0/0          426175 2016-12-14 12:17 strace-4.15/configure

**Comment by skarnet** [comment]
This is not the case with the tarball found at [https://github.com/strace/strace/archive/v4.15.tar.gz]. Could you please tell me what the correct link to the "official" release tarball is?

**Comment by ldv-alt** [comment]
https://sourceforge.net/projects/strace/files/latest/download

**Comment by ldv-alt** [comment]
strace project has never used github for publication of release tarballs, strace-4.15.tar.xz is the first release tarball that  has been uploaded to https://github.com/strace/strace/releases/.
