### ISSUE TITLE
Print SELinux contexts

### ISSUE THREAD

**Issue by esyr** [strace/strace#45]
From https://sourceforge.net/p/strace/patches/13/
Patch: [strace-4.5.8-strace-4.5.8X.diff.txt](https://github.com/strace/strace/files/1767800/strace-4.5.8-strace-4.5.8X.diff.txt) (by John D. Ramsdell, @ramsdell, presumably)

> This patch adds SE Linux security contexts to strace output when the -X option is specified. By using inline functions, the changes causes no overhead when compiled on a system that does not provide SE Linux library functions. The enclosed patch applies to version 4.5.8.

Still relevant. It's probably better to employ `-Z` for that, as a commonly used option for printing SELinux contexts.

**Comment by esyr** [comment]
Note: `-Z` option is used already as `-e status` shorthand.

**Comment by mator** [comment]
lets rework "-Z" to be for selinux ?!

**Comment by esyr** [comment]
Fixed in commit e921913eecd5025dae688fdf9c365023fe3b8a0c and amended in commit ca1aa96f2b00a0dda41506c8eb15bed265066e3a.
