### ISSUE TITLE
Fix -z option

### ISSUE THREAD

**Issue by esyr** [strace/strace#49]
Patch: https://lists.strace.io/pipermail/strace-devel/2017-January/005941.html https://lists.strace.io/pipermail/strace-devel/2017-June/006510.html

**Comment by nikhedonia** [comment]
any reason this hasn't been merged?

**Comment by esyr** [comment]
The implementation is too invasive and there are issues with code style; otherwise, the base idea is good and, actually, it is considered for quite some time for merging, but, unfortunately, my attempts to rework it were sidetracked.

It is probably worth considering increasing priority for this issue, however, as it looks like it has some demand.

**Comment by esyr** [comment]
Debian bug: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=176376
