### ISSUE TITLE
configure: error: failed to find timer_create with LDFLAGS="-static" since 4.22

### ISSUE THREAD

**Issue by ConiKost** [strace/strace#67]
In order to build strace as a static binary, I am using LDFLAGS="-static" for that.
Something has changed between 4.21 and 4.22, as 4.22 seems to fail for me.

Adding "-pthread" seems to fix this issue.
Feel free to close, it not supported.

4.21 (ok)
```
checking for library containing timer_create... -lrt
```

config.log: https://pastebin.com/B9Nc612D

4.22 (fails)
```checking for library containing timer_create... no
configure: error: in `/home/kostecki/strace-4.22':
configure: error: failed to find timer_create
See `config.log' for more details
```

config.log: https://pastebin.com/9tGCfnsw

**Comment by ldv-alt** [comment]
Try LDFLAGS='-static -pthread' instead of plain LDFLAGS='-static'.

**Comment by ConiKost** [comment]
> Well, I don't see any mention of "timer_create" in the provided log; moreover, configure in strace 4.21
> didn't have that check. I presume, the quoted line is from configure run without -static provided.

Yes, it seems, that I've messed something with the logs. You are right with 4.21.

> Try LDFLAGS='-static -pthread' instead of plain LDFLAGS='-static'.

See my post ;-) Adding "-pthread" does the job. Thanks.

**Comment by admzzz** [comment]
ldv-alt,
а вынести этот прикол в какой-нибудь ридми-статик? 
...2ч убито...

**Comment by rubyFeedback** [comment]
I just ran into the problem too. It works when I use the modified LDFLAGS variant, so thanks to all who contributed to this back then.

**Comment by Britripe** [comment]
Benefited a lot, ready to get back to work. Thanks to all the workers!
