### ISSUE TITLE
Error with clang -Werror build: initializer overrides prior initialization of this subobject

### ISSUE THREAD

**Issue by whitequark** [strace/strace#77]
strace 5aba5298543f5409f2a24f8b6a995dcf19d6fa23, clang version 6.0.1-6 (tags/RELEASE_601/final)
```
clang -DHAVE_CONFIG_H   -I./linux/x86_64 -I../linux/x86_64 -I./linux -I../linux -I. -I..      -Wall -Wempty-body -Wformat-security -Wignored-qualifiers -Winit-self -Wnested-externs -Wold-style-definition -Wsign-compare -Wtype-limits -Wwrite-strings -Werror   -g -O2 -MT strace-sock.o -MD -MP -MF .deps/strace-sock.Tpo -c -o strace-sock.o `test -f 'sock.c' || echo '../'`sock.c
../sock.c:86:27: error: initializer overrides prior initialization of this subobject [-Werror,-Winitializer-overrides]
                        [ARPHRD_NETROM]     =  7 /* AX25_ADDR_LEN */,
                                               ^
../sock.c:84:32: note: previous initialization is here
                        [0 ... ARPHRD_IEEE802_TR] = 255,
                                                    ^~~
../sock.c:87:27: error: initializer overrides prior initialization of this subobject [-Werror,-Winitializer-overrides]
                        [ARPHRD_ETHER]      =  6 /* ETH_ALEN */,
                                               ^
../sock.c:84:32: note: previous initialization is here
                        [0 ... ARPHRD_IEEE802_TR] = 255,
                                                    ^~~
```

**Comment by whitequark** [comment]
Why not fix this for all compilers? Otherwise, I guess `-Wno-initializer-overrides` would do the job.

**Comment by ldv-alt** [comment]
I'm very reluctant to disable any gcc warnings just because of clang, and gcc generates no warnings about this code so far.  Could you suggest a mechanism similar to DIAG_PUSH_IGNORE_TAUTOLOGICAL_COMPARE/DIAG_POP_IGNORE_TAUTOLOGICAL_COMPARE to have a more precise control over this warning?

**Comment by whitequark** [comment]
You could use a pragma.
```
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wwhatever"

// ...

#pragma clang diagnostic pop
```

**Comment by ldv-alt** [comment]
Please have a look at the definition of DIAG_PUSH_IGNORE_TAUTOLOGICAL_COMPARE in gcc_compat.h file.  I'd like to keep all compiler-specific pragmas in a separate file.  Could you dig out the minimal version of clang that supports _Pragma and -Winitializer-overrides, please?

**Comment by whitequark** [comment]
Interestingly, the commit message for clang claims it is in `-Wextra` too...
```
commit 57dc2fc543e4cd3def9d27f22349f5b3c6513f4c
Author: Douglas Gregor <dgregor@apple.com>
Date:   Mon Jun 14 21:15:09 2010 +0000

    Put warnings about designated initializations overridding prior
    initializations into their own warning group, initializer-overrides,
    which is part of -Wextra. Patch by william@25thandClement.com, fixes
    PR6934!
```
Anyway, the warning exists since clang 2.8 (which is so absurdly old no one will use it), and `_Pragma` exists more or less since its inception, as far as I can tell.

**Comment by ldv-alt** [comment]
This clang option might have been introduced as `-Wextra` and added to `-Wall` later.
Anyway, I'll try to gag this warning during initialization of `hwaddr_sizes`.

**Comment by whitequark** [comment]
Thanks!
