### ISSUE TITLE
Error with clang -Werror: comparison of integers of different signs: '__u32' (aka 'unsigned int') and 'ssize_t'

### ISSUE THREAD

**Issue by whitequark** [strace/strace#79]
strace 5aba529, clang version 6.0.1-6 (tags/RELEASE_601/final) in `make check`
```
clang-7 -DHAVE_CONFIG_H   -DMPERS_IS_m32 -m32 -I. -I../linux/i386 -I../../linux/i386 -I../linux -I../../linux -I.. -I../.. -DTESTS_SIZEOF_KERNEL_LONG_T=4 -DTESTS_SIZEOF_LONG=4  -Wall -Wempty-body -Wformat-security -Wignored-qualifiers -Winit-self -Wnested-externs -Wold-style-definition -Wsign-compare -Wtype-limits -Wwrite-strings -Werror -Wno-initializer-overrides -Wno-unneeded-internal-declaration -MT nsyscalls.o -MD -MP -MF .deps/nsyscalls.Tpo -c -o nsyscalls.o ../../tests-m32/nsyscalls.c
../../tests-m32/netlink_inet_diag.c:103:7: error: comparison of integers of different signs: '__u32' (aka 'unsigned int') and 'ssize_t'
      (aka 'int') [-Werror,-Wsign-compare]
        if (!NLMSG_OK(h, ret))
             ^~~~~~~~~~~~~~~~
/usr/include/linux/netlink.h:99:24: note: expanded from macro 'NLMSG_OK'
                           (nlh)->nlmsg_len <= (len))
                           ~~~~~~~~~~~~~~~~ ^   ~~~
1 error generated.
```

**Comment by ldv-alt** [comment]
This is a quite old bug in kernel headers, and old gcc versions used to issue the same warning.
Modern gcc correctly treats this as a system headers bug and issues no warnings about this code, though, so could you suggest a clang-only workaround?

**Comment by whitequark** [comment]
Clang does in fact suppress warnings in headers included through `-isystem` paths, but does not suppress such warnings in macros expanded from system headers. Neither does GCC always do it, with exceptions added on case-by-case basis; excerpt from GCC docs:

> Macros defined in a system header are immune to a few warnings wherever they are expanded. This immunity is granted on an ad-hoc basis, when we find that a warning generates lots of false positives because of code in macros defined in system headers.

The macro `NLMSG_LEN` is defined as follows:

```
#define NLMSG_OK(nlh,len) ((len) >= (int)sizeof(struct nlmsghdr) && \
                           (nlh)->nlmsg_len >= sizeof(struct nlmsghdr) && \
                           (nlh)->nlmsg_len <= (len))
```

So, explicitly casting the second argument of `NLMSG_OK` to `__u32` would do the job.

**Comment by ldv-alt** [comment]
If you make the second argument of NLMSG_OK an unsigned integer, then
`(len) >= (int)sizeof(struct nlmsghdr)`
will generate a similar -Wsign-compare warning.
I haven't tried it with clang-6, but I remember it was the case with older versions of gcc.
