### ISSUE TITLE
system call

### ISSUE THREAD

**Issue by UET-HDCien** [strace/strace#84]
Dear Sir,Madam,
My name is Hoang Dang Kien.I'm a researcher in VietNam National University
I run strace on an ELF file in MIPS architecture ,O32 OS and received a result . This is a piece of result.

read(21, "7", 1)                        = 1
read(21, "u", 1)                        = 1
read(21, "4", 1)                        = 1
read(21, "\r", 1)                       = 1
read(21, "\n", 1)                       = 1
svr4_symlink()                          = 4288
svr4_munmap()                           = -1 (errno 4249)
svr4_exit()                             = -1 (errno 4249)
svr4_exit()                             = 4003
getpriority(0x75 /* PRIO_??? */, 144769024) = -1 (errno 4173)
svr4_syscall()                          = -1 (errno 4263)
svr4_syscall()                          = 4263

I looked inside the file /usr/include/mips-linux-gnu/asm/unistd.h. I can see Syscalls as read,exit,syscall, getpriority but I can't see any Syscalls start with svr4. I know that, svr4 Syscalls start at 0 and my OS (O32) Syscall start at 4000. So please explain me , Is svr4_exit is a Syscall or not? And where can I find the systemcall list used by strace? Thank you so much.

**Comment by esyr** [comment]
It looks like lost tracking of entering/exiting syscall state, which is strange, as MIPS O32 used to work[1][2]. Are you using some common distribution (Debian, Gentoo) or something else? What binary are you tracing? Can you provide (or point at) its (or some reproducer's) source code and the command you're running in order to build and trace it?

[1] https://buildd.debian.org/status/fetch.php?pkg=strace&arch=mips&ver=4.21-1&stamp=1519068193&raw=0
[2] https://buildd.debian.org/status/fetch.php?pkg=strace&arch=mipsel&ver=4.21-1&stamp=1519071878&raw=0

**Comment by UET-HDCien** [comment]
Dear Sir,Madam,
I am using embeded linux 32 bit for MIPS , and kernel 3.2.0 (Download from https://people.debian.org/~aurel32/qemu/mips/) . I run them with QEMU in a computer with i386 architecture . I use strace to trace system call when run a malware in virtual machine and sandbbox environment.My command is : 
timeout 30 strace -ff -o filename ./binaryfile 
I don't have source code , here is the binary file and  result when run strace.  (Note that the binary file is a malware). 
[malware.zip](https://github.com/strace/strace/files/2527821/malware.zip)

**Comment by Hello71** [comment]
what is "embeded linux 32 bit for MIPS"? this is not a standard Linux distribution. that kernel is extremely old and obsolete. try modern Debian.

**Comment by ldv-alt** [comment]
An obscure binary running on an 11+ year old kernel for mips o32.
I doubt it would be useful to keep this issue open.
