### ISSUE TITLE
strace -f -- service xxx start  can't stop

### ISSUE THREAD

**Issue by chenkai2017** [strace/strace#9]
hi, 
   i use strace version 4.8 in ubuntu14.  
   when i use  command 'strace -f -- service filebeat start', i found the program can't stop and entering "dead circulation",  but the  filebeat sevice has started.  then i try some other start service, for example,
' service mongo start,  service bigchain start'   and so on,   all of this can't stop , but all of the service have started.

  i try some ways to solve it, but failured.   Does anyone have this problem?

**Comment by ldv-alt** [comment]
> i use strace version 4.8 in ubuntu14.

Note that strace version 4.8 is four years old, the current strace release is 4.17.
Anyway, this is expected behavior: "strace -f -- service NAME start" will follow and trace all processes of service NAME until the last of them terminates.
