### ISSUE TITLE
desc.c:186:35: error: 'print_timeval' undeclared (first use in this function)

### ISSUE THREAD

**Issue by abhisit** [strace/strace#91]
Hi,

I am compiling strace-4.26 on Cygwin64  and cross-compile to AArch64.
I ran those commands.
$ ./configure --prefix=/opt --host=aarch64-linux-gnu --program-prefix=bt- --disable-mpers
$ make -j1
```
desc.c: In function 'sys_oldselect':
desc.c:186:35: error: 'print_timeval' undeclared (first use in this function)
   return decode_select(tcp, args, print_timeval, sprint_timeval);
                                   ^~~~~~~~~~~~~

```

How do I fix this? 

I attached the log files, ./configure and make -j1 too.
[configure.log](https://github.com/strace/strace/files/2843799/configure.log)
[make.log](https://github.com/strace/strace/files/2843800/make.log)

Thank you,
Abhisit.

**Comment by ldv-alt** [comment]
This bug report seems to be outdated.
