### ISSUE TITLE
list of functions the "%file" filter matches

### ISSUE THREAD

**Issue by monoluser** [strace/strace#93]
Good day.

I'd need the full list of function names, that is output by strace with the "-e trace=%file" option.
The one from the manual page ("open,stat,chmod,unlink,...") is obviously not complete.
I'd need this for getting a list of files used by a program I have no access to the source and can't find it myself in the strace source.

Thank you so much for answering! ;)

**Comment by pchaigno** [comment]
All of the syscalls in [`syscallent.h`](https://github.com/strace/strace/blob/7cc6eb706ba7f67d1e84fe903e59ce824f799df5/linux/32/syscallent.h) with the `TF` key are traced by `%file`.

You can see the mapping of `%file` to `TRACE_FILE` in [`basic_filters.c`](https://github.com/strace/strace/blob/7cc6eb706ba7f67d1e84fe903e59ce824f799df5/basic_filters.c#L152) and of `TF` to `TRACE_FILE` in [`sysent_shorthand_defs.h`](https://github.com/strace/strace/blob/7cc6eb706ba7f67d1e84fe903e59ce824f799df5/sysent_shorthand_defs.h#L35).

**Comment by monoluser** [comment]
Oh, cool! Thanks for your fast answer! :)

**Comment by ppiao** [comment]
You can use [asinfo](https://github.com/strace/strace/tree/EdgarKaziakhmedov/asinfo):
$ ./tools/asinfo/asinfo --get-sname %file

asinfo is a project of GSoC 2017:
https://summerofcode.withgoogle.com/archive/2017/projects/5658731350065152/

Thank you.
