### ISSUE TITLE
5.0: test suite on x86_64 is failing with -m32 related issues

### ISSUE THREAD

**Issue by kloczek** [strace/strace#98]
Source code is configured like below:
<pre>+ ./configure --host=x86_64-redhat-linux-gnu --build=x86_64-redhat-linux-gnu --program-prefix= --disable-dependency-tracking --prefix=/usr --exec-prefix=/usr --bindir=/usr/bin --sbindir=/usr/sbin --sysconfdir=/etc --datadir=/usr/share --includedir=/usr/include --libdir=/usr/lib64 --libexecdir=/usr/libexec --localstatedir=/var --sharedstatedir=/var/lib --mandir=/usr/share/man --infodir=/usr/share/info
</pre>
So I'm asking to build x86_64 binaries.
and configure shows:
<pre>checking whether to enable m32 personality support... yes
checking gnu/stubs-x32.h usability... no
checking gnu/stubs-x32.h presence... no
checking for gnu/stubs-x32.h... no
configure: Created empty gnu/stubs-x32.h
checking for mx32 personality compile support... yes
checking for mx32 personality runtime support... no
checking whether mpers.sh mx32 -mx32 works... yes
checking for struct stat... yes
checking for struct stat.st_mtime_nsec... yes
checking for struct stat64... no
checking for struct stat64.st_mtime_nsec... no
checking whether to enable mx32 personality support... yes
checking for valgrind... valgrind
checking for Valgrind tool memcheck... yes
checking for Valgrind tool helgrind... yes
checking for Valgrind tool drd... yes
checking that generated files are newer than configure... done
configure: creating ./config.status
</pre>
and many tests units are failing like below:
<pre>make[4]: Leaving directory &apos;/home/tkloczko/rpmbuild/BUILD/strace-5.0/tests-m32&apos;
make[4]: Entering directory &apos;/home/tkloczko/rpmbuild/BUILD/strace-5.0/tests-m32&apos;
gcc -DHAVE_CONFIG_H   -DMPERS_IS_m32 -m32 -I. -I../linux/i386 -I../linux/i386 -I../linux -I../linux -I.. -I.. -DTESTS_SIZEOF_KERNEL_LONG_T=4 -DTESTS_SIZEOF_LONG=4  -Wall -Wempty-body -Wformat-security -Wignored-qualifiers -Wimplicit-fallthrough=5 -Winit-self -Wlogical-op -Wmissing-parameter-type -Wnested-externs -Wold-style-declaration -Wold-style-definition -Woverride-init -Wsign-compare -Wtype-limits -Wwrite-strings -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -c -o waitid-v.o waitid-v.c
make[4]: Leaving directory &apos;/home/tkloczko/rpmbuild/BUILD/strace-5.0/tests-m32&apos;
make[4]: Entering directory &apos;/home/tkloczko/rpmbuild/BUILD/strace-5.0/tests-m32&apos;
gcc -Wall -Wempty-body -Wformat-security -Wignored-qualifiers -Wimplicit-fallthrough=5 -Winit-self -Wlogical-op -Wmissing-parameter-type -Wnested-externs -Wold-style-declaration -Wold-style-definition -Woverride-init -Wsign-compare -Wtype-limits -Wwrite-strings -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -DMPERS_IS_m32 -m32  -o _newselect _newselect.o libtests.a 
/usr/bin/ld: i386:x86-64 architecture of input file `_newselect.o&apos; is incompatible with i386 output
/usr/bin/ld: i386:x86-64 architecture of input file `libtests.a(libtests_a-error_msg.o)&apos; is incompatible with i386 output
collect2: error: ld returned 1 exit status
make[4]: *** [Makefile:5134: _newselect] Error 1
make[4]: Leaving directory &apos;/home/tkloczko/rpmbuild/BUILD/strace-5.0/tests-m32&apos;
make[4]: Entering directory &apos;/home/tkloczko/rpmbuild/BUILD/strace-5.0/tests-m32&apos;
gcc -Wall -Wempty-body -Wformat-security -Wignored-qualifiers -Wimplicit-fallthrough=5 -Winit-self -Wlogical-op -Wmissing-parameter-type -Wnested-externs -Wold-style-declaration -Wold-style-definition -Woverride-init -Wsign-compare -Wtype-limits -Wwrite-strings -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -DMPERS_IS_m32 -m32  -o accept accept.o libtests.a 
/usr/bin/ld: i386:x86-64 architecture of input file `accept.o&apos; is incompatible with i386 output
/usr/bin/ld: i386:x86-64 architecture of input file `libtests.a(libtests_a-error_msg.o)&apos; is incompatible with i386 output
/usr/bin/ld: i386:x86-64 architecture of input file `libtests.a(libtests_a-sprintrc.o)&apos; is incompatible with i386 output
/usr/bin/ld: i386:x86-64 architecture of input file `libtests.a(libtests_a-tail_alloc.o)&apos; is incompatible with i386 output
/usr/bin/ld: i386:x86-64 architecture of input file `libtests.a(libtests_a-errno2name.o)&apos; is incompatible with i386 output
/usr/bin/ld: i386:x86-64 architecture of input file `libtests.a(libtests_a-get_page_size.o)&apos; is incompatible with i386 output
collect2: error: ld returned 1 exit status
make[4]: *** [Makefile:5142: accept] Error 1
make[4]: Leaving directory &apos;/home/tkloczko/rpmbuild/BUILD/strace-5.0/tests-m32&apos;
make[4]: Entering directory &apos;/home/tkloczko/rpmbuild/BUILD/strace-5.0/tests-m32&apos;
gcc -Wall -Wempty-body -Wformat-security -Wignored-qualifiers -Wimplicit-fallthrough=5 -Winit-self -Wlogical-op -Wmissing-parameter-type -Wnested-externs -Wold-style-declaration -Wold-style-definition -Woverride-init -Wsign-compare -Wtype-limits -Wwrite-strings -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -DMPERS_IS_m32 -m32  -o accept4 accept4.o libtests.a 
/usr/bin/ld: i386:x86-64 architecture of input file `accept4.o&apos; is incompatible with i386 output
/usr/bin/ld: i386:x86-64 architecture of input file `libtests.a(libtests_a-error_msg.o)&apos; is incompatible with i386 output
/usr/bin/ld: i386:x86-64 architecture of input file `libtests.a(libtests_a-sprintrc.o)&apos; is incompatible with i386 output
/usr/bin/ld: i386:x86-64 architecture of input file `libtests.a(libtests_a-tail_alloc.o)&apos; is incompatible with i386 output
/usr/bin/ld: i386:x86-64 architecture of input file `libtests.a(libtests_a-errno2name.o)&apos; is incompatible with i386 output
/usr/bin/ld: i386:x86-64 architecture of input file `libtests.a(libtests_a-get_page_size.o)&apos; is incompatible with i386 output
collect2: error: ld returned 1 exit status
make[4]: *** [Makefile:5146: accept4] Error 1
make[4]: Leaving directory &apos;/home/tkloczko/rpmbuild/BUILD/strace-5.0/tests-m32&apos;
make[4]: Entering directory &apos;/home/tkloczko/rpmbuild/BUILD/strace-5.0/tests-m32&apos;
gcc -Wall -Wempty-body -Wformat-security -Wignored-qualifiers -Wimplicit-fallthrough=5 -Winit-self -Wlogical-op -Wmissing-parameter-type -Wnested-externs -Wold-style-declaration -Wold-style-definition -Woverride-init -Wsign-compare -Wtype-limits -Wwrite-strings -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -DMPERS_IS_m32 -m32  -o access access.o libtests.a 
/usr/bin/ld: i386:x86-64 architecture of input file `access.o&apos; is incompatible with i386 output
/usr/bin/ld: i386:x86-64 architecture of input file `libtests.a(libtests_a-errno2name.o)&apos; is incompatible with i386 output
/usr/bin/ld: i386:x86-64 architecture of input file `libtests.a(libtests_a-error_msg.o)&apos; is incompatible with i386 output
collect2: error: ld returned 1 exit status
make[4]: *** [Makefile:5150: access] Error 1
make[4]: Leaving directory &apos;/home/tkloczko/rpmbuild/BUILD/strace-5.0/tests-m32&apos;
make[4]: Entering directory &apos;/home/tkloczko/rpmbuild/BUILD/strace-5.0/tests-m32&apos;
</pre>

**Comment by ldv-alt** [comment]
Please remove -m64 from your CFLAGS.

**Comment by kloczek** [comment]
Can you tell why just this project must be treated so specially/exceptionally?

**Comment by ldv-alt** [comment]
`-m64` in `CFLAGS` is not compatible with virtually every project that uses `-m32` or `-mx32` or `-m31` for build and honors user-specified `CFLAGS`.

Please report this to the provider of your `CFLAGS` which seems to be redhat.
